package imageprovision

import (
	"fmt"
	"os"

	"github.com/open-edge-platform/image-composer-tool/internal/config"
)

const (
	// aptPolicyPrefsFile pins the distribution archives on immutable images.
	// Template repositories are pinned by their own preferences.d files (see
	// config.generateAptPreferencesFromRepositories), which also apply
	// systemConfig.aptPolicy.
	aptPolicyPrefsFile = "etc/apt/preferences.d/00-ict-apt-policy"
	// unattendedUpgradesFile sorts after the distribution's 50unattended-upgrades.
	unattendedUpgradesFile = "etc/apt/apt.conf.d/52ict-unattended-upgrades"
)

// distroOrigins maps target.os to the Origin field of its archive Release files.
var distroOrigins = map[string]string{
	"ubuntu": "Ubuntu",
	"debian": "Debian",
}

// unattendedUpgradesDisabled clears the distribution default origins so
// unattended-upgrades has nothing it may upgrade on an immutable image.
const unattendedUpgradesDisabled = `// Generated by image-composer-tool: immutable image, no automatic upgrades.
#clear Unattended-Upgrade::Allowed-Origins;
#clear Unattended-Upgrade::Origins-Pattern;
`

// WriteAptPolicy stops the distribution archives from upgrading installed
// packages on an immutable image. Mutable images keep receiving OS and
// security updates; there, systemConfig.aptPolicy only restricts template
// repositories, through their per-repository pins.
func WriteAptPolicy(installRoot string, template *config.ImageTemplate) error {
	origin, ok := distroOrigins[template.Target.OS]
	if !template.SystemConfig.Immutability.Enabled || !ok {
		return nil
	}
	prefs := fmt.Sprintf("# Generated by image-composer-tool: immutable image, no package upgrades.\n"+
		"Package: *\nPin: release o=%s\nPin-Priority: %d\n", origin, config.NoUpgradePinPriority)
	return withRoot(installRoot, func(root *os.Root) error {
		if err := writeFile(root, aptPolicyPrefsFile, []byte(prefs), 0644); err != nil {
			return err
		}
		if err := writeFile(root, unattendedUpgradesFile, []byte(unattendedUpgradesDisabled), 0644); err != nil {
			return err
		}
		log.Infof("Configured APT to block package upgrades on the immutable image")
		return nil
	})
}
