package imageprovision

import (
	"fmt"
	"os"

	"github.com/open-edge-platform/image-composer-tool/internal/config"
)

// ConfigureCloudInit pins cloud-init to the NoCloud seed shipped in the
// image. When the template supplied no meta-data, a first-boot unit generates
// it, so every deployed system gets its own instance-id even when the image
// is a raw artifact that is cloned. The seed files themselves are copied as
// additionalFiles before this runs.
// Pinning the datasource stops ds-identify from probing for cloud metadata
// services, which would otherwise delay first boot on bare metal.
func ConfigureCloudInit(installRoot string, ci config.CloudInitConfig, hostname string) error {
	if !ci.IsEnabled() {
		return nil
	}
	return withRoot(installRoot, func(root *os.Root) error {
		datasource := rel(config.CloudInitConfigDir + "/" + config.CloudInitDatasourceFile)
		content := "# Generated by image-composer-tool\ndatasource_list: [ NoCloud, None ]\n"
		if err := writeFile(root, datasource, []byte(content), 0644); err != nil {
			return err
		}
		// NoCloud is only detected when both meta-data and user-data exist, so
		// generate whichever the template did not supply.
		userData := rel(config.CloudInitSeedDir + "/user-data")
		if _, err := root.Stat(userData); err != nil {
			if err := writeFile(root, userData, []byte("#cloud-config\n{}\n"), 0644); err != nil {
				return err
			}
		}
		if _, err := root.Stat(rel(config.CloudInitSeedDir + "/meta-data")); err != nil {
			if err := installMetaDataUnit(root, hostname); err != nil {
				return err
			}
		}
		log.Infof("Configured cloud-init NoCloud datasource")
		return nil
	})
}

const (
	metaDataScript = config.CloudInitMetaDataScript
	metaDataUnit   = config.CloudInitMetaDataUnit
)

// installMetaDataUnit installs a oneshot unit, ordered before
// cloud-init-local, that writes the NoCloud meta-data on first boot.
func installMetaDataUnit(root *os.Root, hostname string) error {
	if err := writeFile(root, rel(metaDataScript), []byte(renderMetaDataScript(hostname)), 0755); err != nil {
		return err
	}
	unit := "# Generated by image-composer-tool\n[Unit]\n" +
		"Description=ICT cloud-init NoCloud meta-data\n" +
		"DefaultDependencies=no\nAfter=local-fs.target\nBefore=cloud-init-local.service\n" +
		"ConditionPathExists=!" + config.CloudInitSeedDir + "/meta-data\n\n" +
		"[Service]\nType=oneshot\nExecStart=" + metaDataScript + "\n\n" +
		"[Install]\nWantedBy=multi-user.target\n"
	if err := writeFile(root, unitDir+"/"+metaDataUnit, []byte(unit), 0644); err != nil {
		return err
	}
	if err := root.MkdirAll(wantsDir, 0755); err != nil {
		return fmt.Errorf("creating /%s: %w", wantsDir, err)
	}
	return enableUnit(root, metaDataUnit)
}

// renderMetaDataScript returns the script that writes NoCloud meta-data. The
// instance-id comes from the kernel's random UUID at first boot, so it is
// unique per deployed system. The hostname is validated as an RFC 1123 name.
func renderMetaDataScript(hostname string) string {
	script := "#!/bin/sh\n# Generated by image-composer-tool\nset -e\n" +
		"dir=" + config.CloudInitSeedDir + "\nmkdir -p \"$dir\"\n" +
		"{\n  echo \"instance-id: iid-$(cat /proc/sys/kernel/random/uuid)\"\n"
	if hostname != "" {
		script += "  echo \"local-hostname: " + hostname + "\"\n"
	}
	return script + "} > \"$dir/meta-data\"\n"
}
