package imageprovision

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"

	"github.com/open-edge-platform/image-composer-tool/internal/config"
)

const (
	unitDir = "etc/systemd/system"
	// wantsDir is where `systemctl enable` would link a WantedBy=multi-user.target unit.
	wantsDir = unitDir + "/multi-user.target.wants"
	// StampDir records completed first-boot scripts on the deployed system.
	StampDir = config.ProvisioningStampDir
)

// ProvisioningUnitName returns the unit name for the index-th script in
// execution order. The zero-padded index keeps `systemctl list-units`
// sorted in run order.
func ProvisioningUnitName(index int, script config.ProvisioningScript) string {
	return fmt.Sprintf("ict-provision-%03d-%s.service", index, script.Name)
}

// ConfigureProvisioningScripts makes each script executable and installs an
// enabled oneshot unit for it. Units run after network-online.target, in the
// given order; each unit requires the previous one, so a failed script stops
// the scripts after it. A first-boot script's unit writes
// a stamp file only when the script succeeds, so a failed script is retried
// on the next boot; every-boot scripts run on each boot.
func ConfigureProvisioningScripts(installRoot string, scripts []config.ProvisioningScript) error {
	if len(scripts) == 0 {
		return nil
	}
	return withRoot(installRoot, func(root *os.Root) error {
		if err := root.MkdirAll(wantsDir, 0755); err != nil {
			return fmt.Errorf("creating /%s: %w", wantsDir, err)
		}
		previous := ""
		for i, script := range scripts {
			info, err := root.Stat(rel(script.Final))
			if err != nil {
				return fmt.Errorf("provisioning script %s: %s is missing from the image: %w",
					script.Name, script.Final, err)
			}
			if !info.Mode().IsRegular() {
				return fmt.Errorf("provisioning script %s: %s is not a regular file in the image "+
					"(final must be the script's own path, not a directory)", script.Name, script.Final)
			}
			if err := root.Chmod(rel(script.Final), 0755); err != nil {
				return fmt.Errorf("provisioning script %s: making %s executable: %w",
					script.Name, script.Final, err)
			}
			unit := ProvisioningUnitName(i, script)
			unitFile := []byte(renderProvisioningUnit(script, previous))
			if err := writeFile(root, unitDir+"/"+unit, unitFile, 0644); err != nil {
				return err
			}
			if err := enableUnit(root, unit); err != nil {
				return err
			}
			previous = unit
		}
		log.Infof("Installed %d boot-time provisioning unit(s)", len(scripts))
		return nil
	})
}

func renderProvisioningUnit(script config.ProvisioningScript, after string) string {
	firstBoot := script.Stage != config.ProvisioningStageEveryBoot
	stamp := StampDir + "/" + script.Name
	var b strings.Builder
	b.WriteString("# Generated by image-composer-tool\n[Unit]\n")
	fmt.Fprintf(&b, "Description=ICT provisioning script %s\n", script.Name)
	b.WriteString("Wants=network-online.target\nAfter=network-online.target")
	if after != "" {
		b.WriteString(" " + after)
	}
	b.WriteString("\n")
	if after != "" {
		// Requires= (not just After=) so a failed script stops the ones after it.
		fmt.Fprintf(&b, "Requires=%s\n", after)
	}
	if firstBoot {
		fmt.Fprintf(&b, "ConditionPathExists=!%s\n", stamp)
	}
	b.WriteString("\n[Service]\nType=oneshot\nRemainAfterExit=yes\n")
	// systemd expands %-specifiers in ExecStart; escape literal percent signs.
	fmt.Fprintf(&b, "ExecStart=%s\n", strings.ReplaceAll(script.Final, "%", "%%"))
	if firstBoot {
		fmt.Fprintf(&b, "ExecStartPost=/usr/bin/mkdir -p %s\n", StampDir)
		fmt.Fprintf(&b, "ExecStartPost=/usr/bin/touch %s\n", stamp)
	}
	b.WriteString("StandardOutput=journal+console\nStandardError=journal+console\n")
	b.WriteString("\n[Install]\nWantedBy=multi-user.target\n")
	return b.String()
}

// enableUnit creates the multi-user.target.wants symlink, which is exactly
// what `systemctl enable` does for a WantedBy=multi-user.target unit.
func enableUnit(root *os.Root, unit string) error {
	link := wantsDir + "/" + unit
	if err := root.Remove(link); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("replacing /%s: %w", link, err)
	}
	if err := root.Symlink("/"+unitDir+"/"+unit, link); err != nil {
		return fmt.Errorf("enabling %s: %w", unit, err)
	}
	return nil
}
