package imageprovision

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"

	"github.com/open-edge-platform/image-composer-tool/internal/config"
)

const (
	unitDir = "etc/systemd/system"
	// wantsDir is where `systemctl enable` would link a WantedBy=multi-user.target unit.
	wantsDir = unitDir + "/multi-user.target.wants"
	// ProvisioningTriggerUnit starts the script units at boot. The script units
	// are in no target's wants directory: multi-user.target is implicitly
	// ordered after every unit it wants, and cloud-init's cloud-final.service is
	// ordered after multi-user.target, so a wanted unit that is also After=
	// cloud-final.service is an ordering cycle and systemd drops its job.
	ProvisioningTriggerUnit = "ict-provision-start.service"
	// StampDir records completed first-boot scripts on the deployed system.
	StampDir = config.ProvisioningStampDir
)

// ProvisioningUnitName returns the unit name for the index-th script in
// execution order. The zero-padded index keeps `systemctl list-units`
// sorted in run order.
func ProvisioningUnitName(index int, script config.ProvisioningScript) string {
	return fmt.Sprintf("ict-provision-%03d-%s.service", index, script.Name)
}

// ConfigureProvisioningScripts makes each script executable and installs a
// oneshot unit for it, started at boot by an enabled trigger unit. Units run
// after network-online.target and, when cloud-init is running, after
// cloud-final.service, in the given order; each unit requires the previous one,
// so a failed script stops the scripts after it. A first-boot script's unit
// writes a stamp file only when the script succeeds, so a failed script is
// retried on the next boot; every-boot scripts run on each boot.
func ConfigureProvisioningScripts(installRoot string, scripts []config.ProvisioningScript) error {
	if len(scripts) == 0 {
		return nil
	}
	return withRoot(installRoot, func(root *os.Root) error {
		if err := root.MkdirAll(wantsDir, 0755); err != nil {
			return fmt.Errorf("creating /%s: %w", wantsDir, err)
		}
		previous := ""
		units := make([]string, 0, len(scripts))
		for i, script := range scripts {
			info, err := root.Stat(rel(script.Final))
			if err != nil {
				return fmt.Errorf("provisioning script %s: %s is missing from the image: %w",
					script.Name, script.Final, err)
			}
			if !info.Mode().IsRegular() {
				return fmt.Errorf("provisioning script %s: %s is not a regular file in the image "+
					"(final must be the script's own path, not a directory)", script.Name, script.Final)
			}
			if err := root.Chmod(rel(script.Final), 0755); err != nil {
				return fmt.Errorf("provisioning script %s: making %s executable: %w",
					script.Name, script.Final, err)
			}
			unit := ProvisioningUnitName(i, script)
			unitFile := []byte(renderProvisioningUnit(script, previous))
			if err := writeFile(root, unitDir+"/"+unit, unitFile, 0644); err != nil {
				return err
			}
			units = append(units, unit)
			previous = unit
		}
		triggerFile := []byte(renderProvisioningTrigger(units))
		if err := writeFile(root, unitDir+"/"+ProvisioningTriggerUnit, triggerFile, 0644); err != nil {
			return err
		}
		if err := enableUnit(root, ProvisioningTriggerUnit); err != nil {
			return err
		}
		log.Infof("Installed %d boot-time provisioning unit(s)", len(scripts))
		return nil
	})
}

func renderProvisioningUnit(script config.ProvisioningScript, after string) string {
	firstBoot := script.Stage != config.ProvisioningStageEveryBoot
	stamp := StampDir + "/" + script.Name
	var b strings.Builder
	b.WriteString("# Generated by image-composer-tool\n[Unit]\n")
	fmt.Fprintf(&b, "Description=ICT provisioning script %s\n", script.Name)
	// cloud-final.service is where cloud-init applies packages, users, and
	// runcmd, so scripts must wait for it. Ordering against a unit that is not
	// installed is ignored by systemd, so images without cloud-init are unaffected.
	b.WriteString("Wants=network-online.target\nAfter=network-online.target cloud-final.service")
	if after != "" {
		b.WriteString(" " + after)
	}
	b.WriteString("\n")
	if after != "" {
		// Requires= (not just After=) so a failed script stops the ones after it.
		fmt.Fprintf(&b, "Requires=%s\n", after)
	}
	if firstBoot {
		fmt.Fprintf(&b, "ConditionPathExists=!%s\n", stamp)
	}
	b.WriteString("\n[Service]\nType=oneshot\nRemainAfterExit=yes\n")
	// systemd expands %-specifiers in ExecStart; escape literal percent signs.
	fmt.Fprintf(&b, "ExecStart=%s\n", strings.ReplaceAll(script.Final, "%", "%%"))
	if firstBoot {
		fmt.Fprintf(&b, "ExecStartPost=/usr/bin/mkdir -p %s\n", StampDir)
		fmt.Fprintf(&b, "ExecStartPost=/usr/bin/touch %s\n", stamp)
	}
	b.WriteString("StandardOutput=journal+console\nStandardError=journal+console\n")
	return b.String()
}

// renderProvisioningTrigger renders the unit that queues the script units
// without waiting for them: --no-block is what lets a script ordered after
// cloud-final.service start although multi-user.target is reached first, and
// the units run whether or not cloud-init does.
func renderProvisioningTrigger(units []string) string {
	return "# Generated by image-composer-tool\n[Unit]\nDescription=ICT provisioning trigger\n\n" +
		"[Service]\nType=oneshot\n" +
		"ExecStart=/usr/bin/systemctl start --no-block " + strings.Join(units, " ") + "\n\n" +
		"[Install]\nWantedBy=multi-user.target\n"
}

// enableUnit creates the multi-user.target.wants symlink, which is exactly
// what `systemctl enable` does for a WantedBy=multi-user.target unit.
func enableUnit(root *os.Root, unit string) error {
	link := wantsDir + "/" + unit
	if err := root.Remove(link); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("replacing /%s: %w", link, err)
	}
	if err := root.Symlink("/"+unitDir+"/"+unit, link); err != nil {
		return fmt.Errorf("enabling %s: %w", unit, err)
	}
	return nil
}
