package imageprovision

import (
	"fmt"
	"os"
	"strings"

	"github.com/open-edge-platform/image-composer-tool/internal/config"
)

// IsKeyOnlySudoUser reports whether the user has sudo access (the sudo flag or
// an admin group) and a locked password because only SSH keys were configured.
func IsKeyOnlySudoUser(user config.UserConfig) bool {
	return user.HasSudoAccess() && user.Password == "" && len(user.SSHAuthorizedKeys) > 0
}

// WriteKeyOnlySudoers grants passwordless sudo to the key-only sudo users.
// Their password is locked, so the default %sudo policy (which asks for the
// user's own password) could never authenticate them. The grant is limited to
// users with sudo access that have SSH keys and no password, and
// goes in one drop-in file with mode 0440.
func WriteKeyOnlySudoers(installRoot string, users []config.UserConfig) error {
	var lines []string
	for _, u := range users {
		if !IsKeyOnlySudoUser(u) {
			continue
		}
		// Every name the account contract accepts (letters, digits, "_", ".",
		// "-") is a plain sudoers word. Anything else could inject syntax.
		if !config.IsValidUnixUserName(u.Name) {
			return fmt.Errorf("user %q cannot be given key-only sudo: not a valid account name", u.Name)
		}
		lines = append(lines, u.Name+" ALL=(ALL:ALL) NOPASSWD:ALL")
	}
	if len(lines) == 0 {
		return nil
	}
	content := "# Generated by image-composer-tool: sudo users with SSH keys and a locked password\n" +
		strings.Join(lines, "\n") + "\n"
	return withRoot(installRoot, func(root *os.Root) error {
		if err := writeFile(root, rel(config.KeyOnlySudoersFile), []byte(content), 0440); err != nil {
			return err
		}
		log.Infof("Granted passwordless sudo to %d key-only user(s)", len(lines))
		return nil
	})
}
