// SPDX-FileCopyrightText: (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

package api

import (
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strings"
)

// SudoersSpec captures everything needed to render the sudoers drop-in that lets
// a non-root `serve --sudo` process build, cancel, and read build artifacts as
// root — and nothing else.
type SudoersSpec struct {
	User    string // service account that runs `serve` (unqualified login name)
	ICTPath string // absolute path to the image-composer-tool binary
	KillCmd string // absolute path sudo will resolve `kill` to (for cancellation)
	CatCmd  string // absolute path sudo will resolve `cat` to (for reading artifacts)
	WorkDir string // absolute build workspace; the cat rule is scoped to this subtree
}

// SudoersDropInName is the recommended filename under /etc/sudoers.d for the
// generated rules. It contains no dots or tildes (sudo ignores such files).
const SudoersDropInName = "image-composer-tool-webui"

// ResolveSudoersSpec builds a SudoersSpec for the current user and the given ICT
// binary and work-dir paths, resolving the kill/cat helper paths the same way
// sudo will at runtime. ictBinary and workDir may be relative or empty; they are
// resolved to absolute paths (empty ictBinary falls back to discovery, empty
// workDir to the serve default) so the generated rules match what the server
// actually execs and reads — sudo matches the command literally, so a relative
// path would never match an absolute NOPASSWD rule.
func ResolveSudoersSpec(ictBinary, workDir string) (SudoersSpec, error) {
	u, err := user.Current()
	if err != nil {
		return SudoersSpec{}, fmt.Errorf("determining current user: %w", err)
	}
	// A root-owned server needs no sudoers rules at all; generating a rule for
	// "root" would be meaningless and misleading.
	if u.Uid == "0" {
		return SudoersSpec{}, fmt.Errorf("running as root: no sudoers rules are needed " +
			"(the server signals and reads build artifacts directly)")
	}

	if ictBinary == "" {
		ictBinary = discoverICTBinary()
	}
	ictAbs, err := filepath.Abs(ictBinary)
	if err != nil {
		return SudoersSpec{}, fmt.Errorf("resolving ICT binary path %q: %w", ictBinary, err)
	}

	// Match server.go's default so the generated cat rule covers where artifacts
	// actually land when the operator doesn't pass --work-dir.
	if workDir == "" {
		workDir = "webui-workspace"
	}
	workAbs, err := filepath.Abs(workDir)
	if err != nil {
		return SudoersSpec{}, fmt.Errorf("resolving work dir %q: %w", workDir, err)
	}

	return SudoersSpec{
		User:    u.Username,
		ICTPath: ictAbs,
		KillCmd: resolveSudoHelper("kill"),
		CatCmd:  resolveSudoHelper("cat"),
		WorkDir: workAbs,
	}, nil
}

// resolveSudoHelper returns the absolute path a sudo invocation of the given
// helper (kill/cat) will resolve to. The server runs `sudo -n kill ...`, and
// sudo resolves a bare command name against its own secure_path (commonly
// /usr/bin:/bin), not the caller's $PATH. We probe the conventional locations in
// secure_path order and fall back to a PATH lookup, then to /usr/bin/<name> so
// the generated rule always names a concrete absolute path (sudoers rules must).
func resolveSudoHelper(name string) string {
	for _, dir := range []string{"/usr/bin", "/bin", "/usr/sbin", "/sbin"} {
		p := filepath.Join(dir, name)
		if fi, err := os.Stat(p); err == nil && !fi.IsDir() && fi.Mode()&0o111 != 0 {
			return p
		}
	}
	if p, err := exec.LookPath(name); err == nil {
		if abs, aerr := filepath.Abs(p); aerr == nil {
			return abs
		}
		return p
	}
	return filepath.Join("/usr/bin", name)
}

// Render returns the sudoers drop-in content for this spec: three scoped
// NOPASSWD rules and an explanatory header. The content is safe to write to
// /etc/sudoers.d/<SudoersDropInName> (validate with `visudo -cf` first).
//
// The three rules are exactly the privileged operations `serve --sudo` performs:
//   - build:  run the image-composer-tool build (needs root for chroot/mount)
//   - kill:   TERM a build's process group to cancel it (root-owned group)
//   - cat:    read a completed build's artifacts (root-owned output files),
//     scoped to the build workspace subtree — not any path on the host
//
// Each is scoped to a single command; the service user gets no blanket sudo.
func (s SudoersSpec) Render() string {
	var b strings.Builder
	b.WriteString("# image-composer-tool web UI (serve --sudo) — scoped passwordless sudo.\n")
	b.WriteString("# Generated by `image-composer-tool serve --print-sudoers`.\n")
	b.WriteString("# Grants the service user root for ONLY these three commands — not blanket sudo.\n")
	b.WriteString("#\n")
	b.WriteString("# SECURITY NOTE on the kill rule: a build's process-group id is not known\n")
	b.WriteString("# ahead of time, so the rule cannot pin it. This grants the service user the\n")
	b.WriteString("# ability to send SIGTERM (only TERM) to ANY process group as root. Accept\n")
	b.WriteString("# this deliberately, or run the server as root on an isolated build host\n")
	b.WriteString("# (no rules needed) instead. See web/README.md.\n")
	b.WriteString("#\n")
	fmt.Fprintf(&b, "%s ALL=(root) NOPASSWD: %s build *\n", s.User, s.ICTPath)
	fmt.Fprintf(&b, "%s ALL=(root) NOPASSWD: %s -TERM -[0-9]*\n", s.User, s.KillCmd)
	// cat is scoped to the workspace subtree (sudo's `*` spans '/'), so the
	// service user can read build artifacts but not arbitrary root-owned files.
	fmt.Fprintf(&b, "%s ALL=(root) NOPASSWD: %s %s/*\n", s.User, s.CatCmd, s.WorkDir)
	return b.String()
}
