//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ArtifactType.
const (
	Image ArtifactType = "image"
	Sbom  ArtifactType = "sbom"
)

// Valid indicates whether the value is a known member of the ArtifactType enum.
func (e ArtifactType) Valid() bool {
	switch e {
	case Image:
		return true
	case Sbom:
		return true
	default:
		return false
	}
}

// Defines values for BuildStatus.
const (
	BuildStatusCancelled  BuildStatus = "cancelled"
	BuildStatusCancelling BuildStatus = "cancelling"
	BuildStatusFailed     BuildStatus = "failed"
	BuildStatusNotStarted BuildStatus = "not-started"
	BuildStatusRunning    BuildStatus = "running"
	BuildStatusSuccess    BuildStatus = "success"
)

// Valid indicates whether the value is a known member of the BuildStatus enum.
func (e BuildStatus) Valid() bool {
	switch e {
	case BuildStatusCancelled:
		return true
	case BuildStatusCancelling:
		return true
	case BuildStatusFailed:
		return true
	case BuildStatusNotStarted:
		return true
	case BuildStatusRunning:
		return true
	case BuildStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for CancelAcceptedStatus.
const (
	CancelAcceptedStatusCancelling CancelAcceptedStatus = "cancelling"
)

// Valid indicates whether the value is a known member of the CancelAcceptedStatus enum.
func (e CancelAcceptedStatus) Valid() bool {
	switch e {
	case CancelAcceptedStatusCancelling:
		return true
	default:
		return false
	}
}

// Defines values for DiskOverrideArtifactsCompression.
const (
	Gz   DiskOverrideArtifactsCompression = "gz"
	Gzip DiskOverrideArtifactsCompression = "gzip"
	Xz   DiskOverrideArtifactsCompression = "xz"
	Zstd DiskOverrideArtifactsCompression = "zstd"
)

// Valid indicates whether the value is a known member of the DiskOverrideArtifactsCompression enum.
func (e DiskOverrideArtifactsCompression) Valid() bool {
	switch e {
	case Gz:
		return true
	case Gzip:
		return true
	case Xz:
		return true
	case Zstd:
		return true
	default:
		return false
	}
}

// Defines values for DiskOverrideArtifactsType.
const (
	Qcow2 DiskOverrideArtifactsType = "qcow2"
	Raw   DiskOverrideArtifactsType = "raw"
	Tar   DiskOverrideArtifactsType = "tar"
	Vdi   DiskOverrideArtifactsType = "vdi"
	Vhd   DiskOverrideArtifactsType = "vhd"
	Vhdx  DiskOverrideArtifactsType = "vhdx"
	Vmdk  DiskOverrideArtifactsType = "vmdk"
)

// Valid indicates whether the value is a known member of the DiskOverrideArtifactsType enum.
func (e DiskOverrideArtifactsType) Valid() bool {
	switch e {
	case Qcow2:
		return true
	case Raw:
		return true
	case Tar:
		return true
	case Vdi:
		return true
	case Vhd:
		return true
	case Vhdx:
		return true
	case Vmdk:
		return true
	default:
		return false
	}
}

// Defines values for DiskOverridePartitionTableType.
const (
	Gpt DiskOverridePartitionTableType = "gpt"
	Mbr DiskOverridePartitionTableType = "mbr"
)

// Valid indicates whether the value is a known member of the DiskOverridePartitionTableType enum.
func (e DiskOverridePartitionTableType) Valid() bool {
	switch e {
	case Gpt:
		return true
	case Mbr:
		return true
	default:
		return false
	}
}

// Defines values for DiskOverridePartitionsFsType.
const (
	Ext2      DiskOverridePartitionsFsType = "ext2"
	Ext3      DiskOverridePartitionsFsType = "ext3"
	Ext4      DiskOverridePartitionsFsType = "ext4"
	Fat16     DiskOverridePartitionsFsType = "fat16"
	Fat32     DiskOverridePartitionsFsType = "fat32"
	LinuxSwap DiskOverridePartitionsFsType = "linux-swap"
	Vfat      DiskOverridePartitionsFsType = "vfat"
	Xfs       DiskOverridePartitionsFsType = "xfs"
)

// Valid indicates whether the value is a known member of the DiskOverridePartitionsFsType enum.
func (e DiskOverridePartitionsFsType) Valid() bool {
	switch e {
	case Ext2:
		return true
	case Ext3:
		return true
	case Ext4:
		return true
	case Fat16:
		return true
	case Fat32:
		return true
	case LinuxSwap:
		return true
	case Vfat:
		return true
	case Xfs:
		return true
	default:
		return false
	}
}

// Defines values for DiskOverrideSelectionPolicyStrategy.
const (
	Fastest DiskOverrideSelectionPolicyStrategy = "fastest"
	First   DiskOverrideSelectionPolicyStrategy = "first"
	Largest DiskOverrideSelectionPolicyStrategy = "largest"
)

// Valid indicates whether the value is a known member of the DiskOverrideSelectionPolicyStrategy enum.
func (e DiskOverrideSelectionPolicyStrategy) Valid() bool {
	switch e {
	case Fastest:
		return true
	case First:
		return true
	case Largest:
		return true
	default:
		return false
	}
}

// Defines values for ResidualIssueKind.
const (
	CancellationFailure ResidualIssueKind = "cancellation-failure"
	CleanupFailure      ResidualIssueKind = "cleanup-failure"
)

// Valid indicates whether the value is a known member of the ResidualIssueKind enum.
func (e ResidualIssueKind) Valid() bool {
	switch e {
	case CancellationFailure:
		return true
	case CleanupFailure:
		return true
	default:
		return false
	}
}

// Defines values for ValidationIssueSeverity.
const (
	ValidationIssueSeverityError   ValidationIssueSeverity = "error"
	ValidationIssueSeverityWarning ValidationIssueSeverity = "warning"
)

// Valid indicates whether the value is a known member of the ValidationIssueSeverity enum.
func (e ValidationIssueSeverity) Valid() bool {
	switch e {
	case ValidationIssueSeverityError:
		return true
	case ValidationIssueSeverityWarning:
		return true
	default:
		return false
	}
}

// Artifact defines model for Artifact.
type Artifact struct {
	Name string `json:"name"`
	Path string `json:"path"`

	// Size Human-readable size, e.g. "1.13 GB"
	Size *string      `json:"size,omitempty"`
	Type ArtifactType `json:"type"`
}

// ArtifactType defines model for Artifact.Type.
type ArtifactType string

// ArtifactList defines model for ArtifactList.
type ArtifactList struct {
	Artifacts []Artifact `json:"artifacts"`
	BuildId   string     `json:"buildId"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`
}

// BuildAccepted defines model for BuildAccepted.
type BuildAccepted struct {
	BuildId string `json:"buildId"`

	// LogsUrl SSE endpoint for streaming logs
	LogsUrl string `json:"logsUrl"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`
}

// BuildDetails defines model for BuildDetails.
type BuildDetails struct {
	// Artifacts Partial outputs left on disk after a failed or cancelled build, so the
	// UI can point at their location.
	Artifacts *[]Artifact `json:"artifacts,omitempty"`
	BuildId   string      `json:"buildId"`
	CacheDir  string      `json:"cacheDir"`

	// Command The exact command that ran, for the troubleshoot panel
	Command string  `json:"command"`
	ErrMsg  *string `json:"errMsg,omitempty"`

	// HasLogFile A downloadable log file exists on disk
	HasLogFile bool `json:"hasLogFile"`

	// Residual Warning that a cancelled or failed build may have left the machine needing
	// manual cleanup. Present on `BuildDetails`, the SSE terminal event, and a
	// cancel response.
	Residual *ResidualIssue `json:"residual,omitempty"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`

	// Summary The human-readable summary shown in the Review panel and stored on the
	// build record for the Build Details panel.
	Summary  *ComposeSummary `json:"summary,omitempty"`
	Template string          `json:"template"`

	// TemplateUrl Download URL for the resolved template
	TemplateUrl string `json:"templateUrl"`
	WorkDir     string `json:"workDir"`
}

// BuildList defines model for BuildList.
type BuildList struct {
	Builds []HistoryItem `json:"builds"`

	// ServerTime Server time at response generation, used to correct client clock skew.
	ServerTime time.Time `json:"serverTime"`
}

// BuildRequest Start a build. Carries exactly one of `compose` or `yaml` — never a diff.
//
// Exactly one of the two properties must be present. That constraint is
// machine-checkable via minProperties/maxProperties rather than left as
// prose: a body with neither field, or with both, is invalid and the server
// rejects it with 400 `NO_MATCH`.
//
// `oneOf` would express this more idiomatically, but oapi-codegen turns a
// `oneOf` with sibling properties into a `json.RawMessage` union type with
// custom (un)marshalling and two empty `interface{}` branch aliases —
// generated noise around the hot request path, and oapi-codegen does not
// enforce the constraint at runtime either way. The property-count form
// validates identically for a two-property schema and keeps the generated
// struct a plain pair of optional fields.
type BuildRequest struct {
	// Compose The UI selections that identify one combination, plus any Advanced-mode
	// overrides. The backend uses vertical/sku/platform/os/imageType to look
	// up the matching pre-authored template in the manifest; imageName never
	// participates in that lookup — it is applied afterward, via a generated
	// extends delta over the matched template.
	Compose *ComposeRequest `json:"compose,omitempty"`

	// Yaml Complete template YAML (Advanced tab). Self-contained, not a delta.
	Yaml *string `json:"yaml,omitempty"`
}

// BuildStatus Build lifecycle state. `not-started` is the brief window after the build is
// accepted but before its process group exists (a cancel is already honoured
// there). `cancelling` lasts until the child finishes its own teardown.
type BuildStatus string

// CancelAccepted defines model for CancelAccepted.
type CancelAccepted struct {
	BuildId string `json:"buildId"`

	// Residual Warning that a cancelled or failed build may have left the machine needing
	// manual cleanup. Present on `BuildDetails`, the SSE terminal event, and a
	// cancel response.
	Residual *ResidualIssue       `json:"residual,omitempty"`
	Status   CancelAcceptedStatus `json:"status"`
}

// CancelAcceptedStatus defines model for CancelAccepted.Status.
type CancelAcceptedStatus string

// Combination Maps one valid UI selection to a pre-authored template file.
type Combination struct {
	ImageType string  `json:"imageType"`
	Os        string  `json:"os"`
	Platform  string  `json:"platform"`
	Sku       *string `json:"sku,omitempty"`

	// Template Filename in image-templates/. An empty string marks a planned combination whose template is not yet ready: the UI lists it but grays it out and refuses to compose/build it.
	Template string `json:"template"`
	Vertical string `json:"vertical"`
}

// ComposeRequest The UI selections that identify one combination, plus any Advanced-mode
// overrides. The backend uses vertical/sku/platform/os/imageType to look
// up the matching pre-authored template in the manifest; imageName never
// participates in that lookup — it is applied afterward, via a generated
// extends delta over the matched template.
type ComposeRequest struct {
	// Disk A complete replacement for the matched template's `disk` block, as edited
	// by the Advanced tab's Disk step. Omitted means "not overridden".
	//
	// **This must be the complete block, not a diff.** `extends` merging
	// replaces `disk` wholesale rather than merging field by field
	// (internal/config/merge.go: `if !isEmptyDiskConfig(userTemplate.Disk)`),
	// unlike `systemConfig`, where package lists are unioned. A partial block
	// would therefore drop everything it omitted — including the parent's
	// entire partition table. The UI satisfies this by seeding from the
	// resolved template and editing in place.
	//
	// Field constraints here mirror what the builder accepts, which is
	// narrower than the template schema in several places (the schema types
	// most of these as unconstrained strings). Values that only *degrade* a
	// build rather than failing it — an unrecognised partition `type`, for
	// instance — are left loose here and reported as warnings, so a template
	// carrying one can still round-trip.
	Disk *DiskOverride `json:"disk,omitempty"`

	// ImageName Overrides the matched template's image.name. Omitted or empty means
	// "not overridden" — the matched template's own name is used.
	ImageName *string `json:"imageName,omitempty"`
	ImageType string  `json:"imageType"`
	Os        string  `json:"os"`

	// Packages Packages the Advanced tab's Packages step selected, emitted into the
	// generated delta's `systemConfig.packages`. A pinned version uses the
	// `name_version` form the package resolver matches (e.g.
	// `curl_8.5.0-2ubuntu10.13`); a bare name floats to whatever the
	// repository publishes. The pattern matches the template schema's own
	// constraint on `systemConfig.packages` items.
	//
	// Because the extends merge unions package lists, a pinned entry whose
	// name the matched template already lists unpinned leaves both entries
	// in the resolved template — see `pinConflicts` on the response.
	Packages *[]string `json:"packages,omitempty"`
	Platform string    `json:"platform"`

	// Repos Repository ids (as published by GET /package-repos) the user enabled.
	// Each maps to a `packageRepositories` entry in the generated delta, so
	// a package picked from a repository the matched template doesn't
	// already configure can still resolve at build time. Repositories the
	// catalog marks `enabledByDefault` need not be listed — they come from
	// the per-OS providerconfigs.
	Repos    *[]string `json:"repos,omitempty"`
	Sku      *string   `json:"sku,omitempty"`
	Vertical string    `json:"vertical"`
}

// ComposeResponse defines model for ComposeResponse.
type ComposeResponse struct {
	// BaseYaml The matched template resolved *without* this request's overrides —
	// i.e. what `yaml` would have been had nothing been overridden. Lets a
	// client show the curated baseline beside the delta that modifies it,
	// so the difference is attributable to the user's own choices.
	BaseYaml *string `json:"baseYaml,omitempty"`

	// DeltaYaml The generated `extends` delta, verbatim — only the overrides this
	// request asked for, over a reference to the matched template. Empty
	// when the request carries no overrides, in which case the matched
	// template is resolved directly and no delta is generated.
	DeltaYaml *string `json:"deltaYaml,omitempty"`

	// PinConflicts Packages requested at a pinned version whose name the matched
	// template already lists unpinned. The extends merge unions package
	// lists and cannot remove the parent's entry, so both end up in the
	// resolved template and the resolver may install either. Advisory
	// only: the compose still succeeds.
	PinConflicts *[]string `json:"pinConflicts,omitempty"`

	// Summary The human-readable summary shown in the Review panel and stored on the
	// build record for the Build Details panel.
	Summary ComposeSummary `json:"summary"`

	// Template Resolved template filename
	Template string `json:"template"`

	// Yaml The resolved final template — what building this same request would
	// run. Identical to the matched template's own `resolve --full` output
	// when no overrides are set.
	Yaml string `json:"yaml"`
}

// ComposeSummary The human-readable summary shown in the Review panel and stored on the
// build record for the Build Details panel.
type ComposeSummary struct {
	Architecture string `json:"architecture"`

	// BaseImage Overlay-mode only — the baseline image packages are layered onto.
	BaseImage      *string `json:"baseImage,omitempty"`
	Description    string  `json:"description"`
	DiskSize       string  `json:"diskSize"`
	Hostname       string  `json:"hostname"`
	ImageName      string  `json:"imageName"`
	ImageType      string  `json:"imageType"`
	ImageVersion   string  `json:"imageVersion"`
	KernelVersion  string  `json:"kernelVersion"`
	Os             string  `json:"os"`
	PackageCount   int     `json:"packageCount"`
	PartitionCount int     `json:"partitionCount"`
	PartitionTable string  `json:"partitionTable"`
	Platform       string  `json:"platform"`
	Sku            string  `json:"sku"`
	Vertical       string  `json:"vertical"`
}

// DiskOverride A complete replacement for the matched template's `disk` block, as edited
// by the Advanced tab's Disk step. Omitted means "not overridden".
//
// **This must be the complete block, not a diff.** `extends` merging
// replaces `disk` wholesale rather than merging field by field
// (internal/config/merge.go: `if !isEmptyDiskConfig(userTemplate.Disk)`),
// unlike `systemConfig`, where package lists are unioned. A partial block
// would therefore drop everything it omitted — including the parent's
// entire partition table. The UI satisfies this by seeding from the
// resolved template and editing in place.
//
// Field constraints here mirror what the builder accepts, which is
// narrower than the template schema in several places (the schema types
// most of these as unconstrained strings). Values that only *degrade* a
// build rather than failing it — an unrecognised partition `type`, for
// instance — are left loose here and reported as warnings, so a template
// carrying one can still round-trip.
type DiskOverride struct {
	// Artifacts Output formats the finished image is converted to. This is the axis
	// QCOW2/VHD/VMDK live on; `target.imageType` controls how the image is
	// built and is separate.
	//
	// Which values are legal depends on the image type: RAW and overlay
	// run the qemu-img pipeline (`raw`/`qcow2`/`vhd`/`vhdx`/`vmdk`/`vdi`,
	// optional `gz`/`xz`/`zstd`), WSL2 requires exactly one `tar` + `gz`,
	// and ISO/IMG never run the pipeline at all. `bz2` is absent because
	// no compressor implements it, despite the template schema listing it.
	Artifacts *[]struct {
		Compression *DiskOverrideArtifactsCompression `json:"compression,omitempty"`
		Type        DiskOverrideArtifactsType         `json:"type"`
	} `json:"artifacts,omitempty"`

	// ExtendLastPartitionToFillDisk Forces the last partition's end to "0". Rejected by the template
	// loader for `imageType: iso`, and for `raw` unless the last partition
	// is the rootfs (`mountPoint: /`).
	ExtendLastPartitionToFillDisk *bool `json:"extendLastPartitionToFillDisk,omitempty"`

	// MaxSize Overlay-mode-only ceiling. Must be greater than `size`, and requires
	// `size` to be set; both rules are enforced by the template loader.
	MaxSize *string `json:"maxSize,omitempty"`

	// Name Required by the template schema ($defs.Disk.required).
	Name               string                          `json:"name"`
	PartitionTableType *DiskOverridePartitionTableType `json:"partitionTableType,omitempty"`

	// Partitions The partition table, in on-disk order. `start`/`end` are absolute
	// offsets, not sizes; an `end` of "0" means "the rest of the disk" and
	// is only valid on the last entry.
	Partitions *[]struct {
		End     *string   `json:"end,omitempty"`
		Flags   *[]string `json:"flags,omitempty"`
		FsLabel *string   `json:"fsLabel,omitempty"`

		// FsType Enumerated because this one is a hard failure: the builder
		// rejects anything else outright (imagedisc.go diskPartitionCreate).
		FsType       *DiskOverridePartitionsFsType `json:"fsType,omitempty"`
		Id           *string                       `json:"id,omitempty"`
		Index        *int                          `json:"index,omitempty"`
		MountOptions *string                       `json:"mountOptions,omitempty"`

		// MountPoint Mount path, or "none" for a partition that is not mounted
		// (what the templates write for swap).
		MountPoint *string `json:"mountPoint,omitempty"`
		Name       *string `json:"name,omitempty"`
		Start      *string `json:"start,omitempty"`

		// Type Partition type name (`esp`, `linux-root-amd64`, …). Left as a
		// free string rather than an enum: an unrecognised value makes
		// the builder fall back to a default type instead of failing
		// (imagedisc.go discards the lookup error), so rejecting one
		// here would be stricter than the build and would stop a
		// template that carries it from round-tripping.
		Type *string `json:"type,omitempty"`

		// TypeUUID GPT type GUID, or one of sgdisk's short hex codes ("8300").
		// Passed through to `sgdisk -t`, which is the arbiter.
		TypeUUID *string `json:"typeUUID,omitempty"`
	} `json:"partitions,omitempty"`

	// Path Target disk device for the live installer. Empty enables
	// policy-based selection via `selectionPolicy`. Carried through
	// unchanged from the matched template; the Disk step does not edit it.
	Path *string `json:"path,omitempty"`

	// SelectionPolicy Policy-based disk selection, used when `path` is empty. Carried
	// through unchanged from the matched template; the Disk step does not
	// edit it.
	SelectionPolicy *struct {
		ExcludeRemovable *bool                                `json:"excludeRemovable,omitempty"`
		RequireEmpty     *bool                                `json:"requireEmpty,omitempty"`
		Strategy         *DiskOverrideSelectionPolicyStrategy `json:"strategy,omitempty"`
	} `json:"selectionPolicy,omitempty"`

	// Size Exact disk size in create mode; a grow-only floor in overlay mode.
	// The suffix set is the builder's own (imagedisc.go sizeSuffixesList)
	// and is stricter than it looks: whole numbers only, exact case, no
	// bare byte counts, no TiB.
	Size *string `json:"size,omitempty"`
}

// DiskOverrideArtifactsCompression defines model for DiskOverride.Artifacts.Compression.
type DiskOverrideArtifactsCompression string

// DiskOverrideArtifactsType defines model for DiskOverride.Artifacts.Type.
type DiskOverrideArtifactsType string

// DiskOverridePartitionTableType defines model for DiskOverride.PartitionTableType.
type DiskOverridePartitionTableType string

// DiskOverridePartitionsFsType Enumerated because this one is a hard failure: the builder
// rejects anything else outright (imagedisc.go diskPartitionCreate).
type DiskOverridePartitionsFsType string

// DiskOverrideSelectionPolicyStrategy defines model for DiskOverride.SelectionPolicy.Strategy.
type DiskOverrideSelectionPolicyStrategy string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// HistoryItem One row in the compose history list.
type HistoryItem struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`

	// Summary The human-readable summary shown in the Review panel and stored on the
	// build record for the Build Details panel.
	Summary  *ComposeSummary `json:"summary,omitempty"`
	Template string          `json:"template"`
}

// Manifest The complete configuration manifest, loaded once by the UI on startup.
type Manifest struct {
	Combinations []Combination `json:"combinations"`
	Platforms    []Option      `json:"platforms"`
	Skus         []Option      `json:"skus"`
	Targets      []Target      `json:"targets"`
	Verticals    []Option      `json:"verticals"`
}

// Option A generic {id, displayName} pair used for dropdown labels.
type Option struct {
	DisplayName string `json:"displayName"`
	Id          string `json:"id"`
}

// PackageRepo One repository the Advanced tab can enable/disable.
type PackageRepo struct {
	Description      *string `json:"description,omitempty"`
	DisplayName      string  `json:"displayName"`
	EnabledByDefault bool    `json:"enabledByDefault"`

	// HasCuratedPackages Whether this repository defines any hand-picked "frequently used" packages, i.e. whether `curated=true` on /packages/search can return anything for it. The list itself stays server-side; only this flag is published, so a client can hide a curation control that would yield nothing rather than offering a dead toggle.
	HasCuratedPackages *bool `json:"hasCuratedPackages,omitempty"`

	// HasSigningKey Whether this repository's packages are ever fetched with signature verification, by either of two independent means: a template that enables it carries a `pkey`, so a build verifies it; or the catalog already verifies its Release against a local keyring when the picker searches it. When false, neither applies and a client should say so rather than leave it implicit. Neither the key URL nor the keyring path is published; only this flag is.
	HasSigningKey *bool  `json:"hasSigningKey,omitempty"`
	Id            string `json:"id"`

	// Priority Repository priority (higher number = preferred when packages exist in multiple repos). Default 500.
	Priority *int   `json:"priority,omitempty"`
	Url      string `json:"url"`
}

// PackageRepoList defines model for PackageRepoList.
type PackageRepoList struct {
	Repos []PackageRepo `json:"repos"`
}

// PackageSearchResult One package, with every version of it the search found. A package is
// reported once no matter how many indexes carry it — a Debian-style
// repository publishes the release, -updates and -security suites
// separately, so the same package routinely exists at several versions.
type PackageSearchResult struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`

	// Repository ID of the repository providing `version`.
	Repository string `json:"repository"`

	// Version The newest available version, and the one used when a package is
	// added without pinning. Always equal to `versions[0].version`.
	Version string `json:"version"`

	// Versions Every version found, newest first, each with the repository that
	// provides it — pinning a version therefore also selects a
	// repository. Ordering uses the target's native version comparison
	// (Debian or RPM), not string ordering, so `1:9.6p1-3ubuntu13.9`
	// correctly outranks `1:9.6p1-3ubuntu13.7`.
	Versions *[]PackageVersion `json:"versions,omitempty"`
}

// PackageSearchResults defines model for PackageSearchResults.
type PackageSearchResults struct {
	Packages []PackageSearchResult `json:"packages"`
	Query    string                `json:"query"`
	Total    int                   `json:"total"`
}

// PackageVersion One available version of a package, and where it comes from.
type PackageVersion struct {
	Repository string `json:"repository"`
	Version    string `json:"version"`
}

// ResidualIssue Warning that a cancelled or failed build may have left the machine needing
// manual cleanup. Present on `BuildDetails`, the SSE terminal event, and a
// cancel response.
type ResidualIssue struct {
	// Detail Remediation detail: the failing signal error, or the tool's residual
	// cleanup report including its `mount | grep` / `losetup -l` hint.
	Detail string `json:"detail"`

	// Kind - `cancellation-failure` — the cancel signal could not be delivered (or
	//   the build never exited), so teardown may never have run.
	// - `cleanup-failure` — the build ran its teardown but reported leftover
	//   mounts or loop devices.
	Kind ResidualIssueKind `json:"kind"`
}

// ResidualIssueKind - `cancellation-failure` — the cancel signal could not be delivered (or
//
//		the build never exited), so teardown may never have run.
//	  - `cleanup-failure` — the build ran its teardown but reported leftover
//	    mounts or loop devices.
type ResidualIssueKind string

// Target An OS option with its family and architecture.
type Target struct {
	Arch        string `json:"arch"`
	DisplayName string `json:"displayName"`
	Id          string `json:"id"`
	Os          string `json:"os"`
}

// ValidationIssue defines model for ValidationIssue.
type ValidationIssue struct {
	Message string `json:"message"`

	// Path JSON path to the problematic field
	Path     string                  `json:"path"`
	Severity ValidationIssueSeverity `json:"severity"`
}

// ValidationIssueSeverity defines model for ValidationIssue.Severity.
type ValidationIssueSeverity string

// ValidationResponse defines model for ValidationResponse.
type ValidationResponse struct {
	Errors   *[]ValidationIssue `json:"errors,omitempty"`
	Valid    bool               `json:"valid"`
	Warnings *[]ValidationIssue `json:"warnings,omitempty"`
}

// BuildId defines model for BuildId.
type BuildId = string

// ListPackageReposParams defines parameters for ListPackageRepos.
type ListPackageReposParams struct {
	// Os Filter repos by target OS compatibility, matching an OS the manifest
	// offers — a `targets[].id` or a `combinations[].os` (e.g. `ubuntu24`).
	// Omit to return every repository.
	Os *string `form:"os,omitempty" json:"os,omitempty"`
}

// SearchPackagesParams defines parameters for SearchPackages.
type SearchPackagesParams struct {
	// Q Search query (package name prefix). Omit to browse.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Os Target OS distribution ID (e.g., ubuntu24)
	Os string `form:"os" json:"os"`

	// Repos Filter by enabled repository IDs
	Repos *[]string `form:"repos,omitempty" json:"repos,omitempty"`

	// Limit Max results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of matching results to skip, for paging
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Curated When true, narrow results to each matched repository's hand-picked "frequently used" packages instead of its full catalog. A matched repository with none defined then contributes nothing, rather than falling back to its full catalog.
	Curated *bool `form:"curated,omitempty" json:"curated,omitempty"`
}

// ValidateTemplateJSONBody defines parameters for ValidateTemplate.
type ValidateTemplateJSONBody struct {
	// Yaml Complete template YAML to validate
	Yaml string `json:"yaml"`
}

// StartBuildJSONRequestBody defines body for StartBuild for application/json ContentType.
type StartBuildJSONRequestBody = BuildRequest

// ComposeTemplateJSONRequestBody defines body for ComposeTemplate for application/json ContentType.
type ComposeTemplateJSONRequestBody = ComposeRequest

// ValidateTemplateJSONRequestBody defines body for ValidateTemplate for application/json ContentType.
type ValidateTemplateJSONRequestBody ValidateTemplateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List the compose history
	// (GET /builds)
	ListBuilds(w http.ResponseWriter, r *http.Request)
	// Start an image build
	// (POST /builds)
	StartBuild(w http.ResponseWriter, r *http.Request)
	// List a build's output artifacts
	// (GET /builds/{id}/artifacts)
	ListBuildArtifacts(w http.ResponseWriter, r *http.Request, id BuildId)
	// Cancel a running build
	// (POST /builds/{id}/cancel)
	CancelBuild(w http.ResponseWriter, r *http.Request, id BuildId)
	// Get a build's command, resolved paths, and summary
	// (GET /builds/{id}/details)
	GetBuildDetails(w http.ResponseWriter, r *http.Request, id BuildId)
	// Get the full configuration manifest
	// (GET /manifest)
	GetManifest(w http.ResponseWriter, r *http.Request)
	// List available package repositories
	// (GET /package-repos)
	ListPackageRepos(w http.ResponseWriter, r *http.Request, params ListPackageReposParams)
	// Search available packages
	// (GET /packages/search)
	SearchPackages(w http.ResponseWriter, r *http.Request, params SearchPackagesParams)
	// Resolve the base template for a set of selections
	// (POST /templates/compose)
	ComposeTemplate(w http.ResponseWriter, r *http.Request)
	// Validate an edited template
	// (POST /templates/validate)
	ValidateTemplate(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBuilds operation middleware
func (siw *ServerInterfaceWrapper) ListBuilds(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuilds(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartBuild operation middleware
func (siw *ServerInterfaceWrapper) StartBuild(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartBuild(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBuildArtifacts operation middleware
func (siw *ServerInterfaceWrapper) ListBuildArtifacts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuildArtifacts(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelBuild operation middleware
func (siw *ServerInterfaceWrapper) CancelBuild(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelBuild(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBuildDetails operation middleware
func (siw *ServerInterfaceWrapper) GetBuildDetails(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBuildDetails(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetManifest operation middleware
func (siw *ServerInterfaceWrapper) GetManifest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetManifest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPackageRepos operation middleware
func (siw *ServerInterfaceWrapper) ListPackageRepos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPackageReposParams

	// ------------- Optional query parameter "os" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "os", r.URL.Query(), &params.Os, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "os"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "os", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPackageRepos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPackages operation middleware
func (siw *ServerInterfaceWrapper) SearchPackages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPackagesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Required query parameter "os" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "os", r.URL.Query(), &params.Os, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "os"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "os", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "repos" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "repos", r.URL.Query(), &params.Repos, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "repos"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repos", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "curated" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "curated", r.URL.Query(), &params.Curated, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "curated"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "curated", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPackages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ComposeTemplate operation middleware
func (siw *ServerInterfaceWrapper) ComposeTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ComposeTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateTemplate operation middleware
func (siw *ServerInterfaceWrapper) ValidateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds", wrapper.ListBuilds)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/builds", wrapper.StartBuild)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds/{id}/artifacts", wrapper.ListBuildArtifacts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/builds/{id}/cancel", wrapper.CancelBuild)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds/{id}/details", wrapper.GetBuildDetails)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/manifest", wrapper.GetManifest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/package-repos", wrapper.ListPackageRepos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/packages/search", wrapper.SearchPackages)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/templates/compose", wrapper.ComposeTemplate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/templates/validate", wrapper.ValidateTemplate)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zH39chw3kuer4Po2QqTdHxRlez1UbGzoazRcSyJPpOyYdelc6KrsbgyrgDKAYrNl6WL/2gfYuGe4B5sn",
	"uchMoD66q0l6VvbMPxK7uwoFJBL5+cusX0aZKSujQXs3OvllVEkrS/Bg6dPTWhX5aY5/5uAyqyqvjB6d",
	"8A9C5aC9Wiiw4uDdu9Pnh6PxSOHPlfSr0XikZQmjk5HKR+ORhZ9rZSEfnXhbw3jkshWUEkf2mwqvct4q",
	"vRx9+vQp/khTeGK9WsjM0+SsqcB6BfQLj/7LCG5kWRU4RD2vta+Pv5pYMzdeZW4iSzu1cj1dfhiNtx80",
	"5mnuzmA8cuoD7C76T3Up9cSCzOW8AIEXjQVMl1ORjB5OHz4SL58mo9G4M6Hw7dCz+YtfRqDrcnTy40iV",
	"cgmj8cjNTTl6v3PDpy4Ff+S1h4vCOtp7zPwvkHl8SCTeK+UGCCjDr/RBeSjpj3+ysBidjP7nrGWMWdiP",
	"WbMZzQJG0lq5wc/zlld26emlr+8cnZjqgi/dXnAcvRlr3Jn+0NJpsCdZBpWHfHftt822MEv3zha7DHBx",
	"8UKAziujtBcLY4XzFmSp9FLgPb2tn8lKza4fzuhBbibn2eTh8aNZuO73oVBcyF76PAcvVeHuYI0+Ec7x",
	"N1kIU/uq9k4UsPDCaJErdyXkwoMVUiykKiAXxopM6gwK/EATHAtnhF9Bot+d4m+CiSk9fqmsKEwm8UHT",
	"RKMw+S2ZMpPZCp4rO/yjKUupByTf5QoE3MjMi3CJ8CvphZV6TCzhVyC8NfW8ALcyxotKaiiGthysfe2W",
	"g09fSffKLP+oigEp9ETkZq0LE6RQYZZioQqclHLexZ1oHzg3pgCpR8QuTuW1LO6i6Ntw3alzNfyN3Dke",
	"ubospd3cddcz/MrBRbgaNxHKqpAeBkkTfxw8oM8DZcS7t6+a3bDgTHENuWjGHdiMtbFXw7xw9zGLvNKZ",
	"eX+e7fAdruvt8t4TOiy5WajcW2z/STlv7ObUQzl0SBzYa7CXqhzgtgv6TXhVAh5SC64y2oFYggZLJ3Us",
	"aofENSIz1gIejEKBxv9MdiXcFayno/FoYWwp/ehklEsPExxvNL4PqZHAnQnuJdRb+LkGptXWCry0XkgW",
	"P1PxTFqrwPEZLjbCaBBmIdKM2TBFmZVuZFmk4q//8X+FhmsSaLlaLKaJTvSL/n103NdGtPsjytp5MQdR",
	"WXCg/VRcooDIjHbeShR2yiW6lNlKaZhkK8iu6CBfKylKpc+bgWalvGk/CSv9CndiJTXLXOkSXVnj4ARX",
	"Z/KNWCu/EhoUXbhQgOLWWP56bvxqLJQTSl/LQuWCRRcIJm6iLSA9nVCeb/jq6Eikb85+ev3k8tmfUlp7",
	"ajScLVKxNnWRC7jBFTrhV8qJ0lgQKlemlF5lsig2YzGvvTCyUpPM5LAELXxttROyMxA+yKl5gSq0Q0Kl",
	"vRFSpH9xRk/fyvVrcE4uIRW1VkYL5AC6N9FZ7bwpxUGtD0tp3UoWNBYtbm0ElJXfiFRpD3YhM/jlUyrm",
	"VupsJWShpAOHu5zowM6QC22UAyGtqQN9VgbZnphLoKE1psF768oNOKGNTzTohbEZ0I2dHceTU2s6RGF3",
	"1nKDjAFx1ZtJZmq2KsqEd0h6pASZ2ERQEmgSlzWJNwk+4TSjK4DK0YObxSQ4gTpD7q8KqbSopLLItYYO",
	"hyyYSRwr2x67jU4ejkc9dqRv+mIonJl7Svh4Qj+NR3i+dk8qXleAh0ZQiz8/ef1KHDzJr9GIyIWX88Op",
	"uIBiMcmM9lJpyMdIeDygUHg5HZQpwwLjotFpQ65NoRaQbTI08730MBWpNn7iUJZAnuI5QkrPrYKFWCud",
	"m3Wwfehr9o5comUwQOkszGFBp8Q73PUMz87SmrqKqvtABmsJh5cFOhobsTLa1Bb3EvkGDqciDSaV0stU",
	"FBLvRN4qmOlW+OiF0sqtkH3QIlhr4UFaNBt4p6PP0VkSemi11kgy1FHxAe0HusTVGU4bxTkZeAOOynj0",
	"jG7420zvz2ChxMV1FvF+/GuV+pCaeWbKudKS2WSba17LypFOYOH67lQ4KCDzJK5QllUWJrL2K2M7lghZ",
	"bsi0fQqRL3gZHMQdGhk3+DUOiNJj2AG7qm+1pnYXhGYJeplCaUHzmcRr3WwqnuggWnkoUUp75VjMaA05",
	"2saRVmK9Mq5zphWJSrEBFKsy35wQ3747FQUdAuXprCyt3NAHU3sSbxYWNYprsjNInszCMfPTnuPVBAFu",
	"vv3mp286sYC/yA8fNhPlzHRTDhrk17gDGTPf7fzSXNkhO23MuLN3HeruYaeuVBx0NLps5NjRCDEXNkA6",
	"ZB6LqqidkHojoryclCaHRJtrsFbl4FjhzGV2BToXRM24kJm7qmdxKTPjZs0ykOCFMVeJrivaqVJ6NF2W",
	"ezha6XCVVgtw/jEzzxvkJLKlEl2hA5mpivWb5mXhI+qKTC7lSf5VVaEgZ6m6ljYfk4Uku9oNbjzo3LHs",
	"F+Y6iF+aYWdOLPT6R4x8pDuEzHPlrs4C8XDHmpXsbla8zA1O4IFjKkzxQE3FWam8Z++YD1EJUrtEJyiQ",
	"RdiuHHQyInrsGRHFOh9QRxZ4o8RfgV761ejkm68oMuTB4gz/949y8uHJ5N+PJn94f9D+nSSTn95/0fnt",
	"8F//aehs/G0iSWZXcgmDQQT+hRbX1e8PnGh+cx6qwP+o5yGQjYxDCiG0VhtxwAMnUrdxHspnRi/Uchqf",
	"n07FE1EpkkzXYB1KJRYmOEqKVPwpfJ+SBUbTCndH/9GGTXDiAKbLaaLTrLbFT99Ov54eTY5Z6jw8mj58",
	"lB4+RoNcWuD9WRRGehJc65X0ELgUDe7KOIWOmajqeUEKO9iEvGvNA8nJiAeMuZMZINEdI9PofcsX5CWS",
	"Cf8UMlk7NlDj8SnBLoFNa9esmqTxGEU60w20txuW5YmmdQ3xZWO2sDCvdbi7AHkNjpwQGkmBS3QQFTv+",
	"OXG9AxBppTSupVCZdykuMFxPPuhWiKjD+cdff9Nn/SeTf5eTD8je7Z9f/jQ9+T9f/GuS/Jgk7yfvvxhk",
	"+1LenPIDaMye5zwe1Vr9XEO4wNsa7lLDtOW7p+FtywkqRzvQNRyRi/lGvHxxKWZhYyY0xiFRonZgBWh0",
	"H/H4v5DZSpRoiLD3FO5oRlfICryPgfRbB2gsnEm0bHigUtkV5GJhTSmk6PDr4NajF6Qf+ERHHsiIDWsL",
	"FOhzXhVF3Gz0iFh9o1M0Fd058unIpJeFiZZFGlb5dPMcFrIufCo0kLdGrjZyG+RRWuKT8dxZU5LVLCqw",
	"k7MLNLqvVQ6W5+W2+OeWvUdJeo+t32dkfWa74lZjgo/GgNEtHfx50Ou6HNrL5kx+gW62qf0X7OYHRxil",
	"T6PxyIFWU5iSfIvBE44RrOQ1iDmAFitJu0WWA33R6rmpeAWe4gIhcuRWZs3eTM3cibMvlMahnMpZ9LDS",
	"J+OhNLlaUNzAjxPNAWaK2IAFnZGGlN5bNa89hVpYf9DxCYo0WxmVQWCJnQ2kR+2nXnuK0iBS03iersHO",
	"pVclsabRBR8d07EW0EuM4QXp6LgZO2ZjBs9cXEOY845tI16gCZHo9QqieOTBshDo0qZ93hgP/nqlspXI",
	"pOuJ8ER3LfRm/3NlgeJdaINrE6iuXLvoPTTriu5b9H+YLRp6vlU2UUmz67CtbTpTHVY3rEVvU2+J5jtw",
	"VZnUmmI8pbmGoPktaGRyEpaUsgiaKxd1FYQnbtu24ooxtY7JgLLWeVkUIfIzRXNHOWM3iUaGOAmxIjq/",
	"QUiSmw35nRJqJ5D7OSLu26ppe42L4BgObfpm7xlpaLVQWhZ9VU9ig7QBCgeSMw63PHIyiZJE21pPxWmM",
	"h+07EOFAp1HRTCaLuijSkK4K56R7JgQaag78IB9vyedOfJ+W2pL8FqF80e7KLl1WWzllvpYkoI5a+i1c",
	"K1hzIolYzHnyuUzgQ1akFjJj8ybrwWGskODje4f8IGmzlfKQ+doOm/Yoek8pNz3o9BRyQ24mC7forjTy",
	"mrRWPHRM6kJugGfvzXRY2nYeMjAjdN0uQoJ+N3NmnI/AgGEn5s2tv+51cejX71kuDV5wBVZDcdsVt3tJ",
	"z0ytfecCpT0swfIV1iukx32uuURG+nwRor/JeMHBbg+NtFuxRdr+/o/7DLpN5S3idXhjh2g7FOrwytDh",
	"7Tn/eFDyXHHQvBsSX8jCwXgnQ5vFSLaFqpAZlBAAA3skVorzTsW8MNnVWEgnIFcU4ZhvhjxknBt5x20s",
	"gUIIYjeCQE7fF19cUo4mJKaiwqEZhmeGILpaLKZffNGxY1B5Kr0kbxVX0sx1vTIFOFlALzEVLue8Arou",
	"9EeiDygDo2UxY+N7Rkp5ujQnIlUL8T+UIzMGF8bO6wEaZ5fRyMHvD9PDcaJrXagr6Du66VisV2Ch77uS",
	"sCGtjwbBE1EF3AItONFsn1JMnaLyuTWVQOd8wzaq8sIE2lJQSmdFHfRTayAkqFgVPTnwliALkw2Qd6fC",
	"Sa/cQgVLDwniAGgYcqpuMSOQA2geWhDhaSP/SGRtfX4naN2lstZY1qNN/gHtR4rBu3Ew+dDU1NJas47b",
	"NRBYwAc6pIMsRNjxA0oT8q94TlyiS+N8SH86QIat20gE5CEq7A6n4ntZ1BBCl6QivshhaWUOX6C9HzRX",
	"h4EWUhWB/Eh2qUWtUbMttXKQd+ic4kxSwlwkmkwstJLpHlQysKCYogOmEEeQK2PJ0nRiLa3GGZJtJxsa",
	"oNtp7QYnQOHV1m01tc4n3qpqWInuRcuckdkhOPvNkZyQnMmDclQONxSFJ2XRkXWUiwkmeYOb9r+enf1w",
	"PPv+T89n379+/p0o1DXq28ci9dIuwU8bwZriUN6awonoQsWHMLE5lo4GFlTScmw00T8Qe1zzVjH5lrIQ",
	"OVRkQIe4C4+EZD8Rb5/8wGlQNgHIOKOLfoaynqhyKSpVsQlwkFq5Tmfpz5lZH6ez9HqV8783+F+ZX+F/",
	"uUrHiW7SkunyQzpLb/CfD87n6eFY/HDx6lgEddPP3iMVUvEl3TRONE7r9OJsdvr6Zcjex7k1U0JXoyim",
	"Ip1/OKZcnpw7lNBzDo4lWnOSwYJzxgqFohJFODmYIgdXKQ+DhwclD7Pvlu1+q/rYzarik4MZEfNZBGFc",
	"flDVaDy6wb+RMoMJuG1ooZXr0XhE9B+NR9ernP+9wf/K/Ar/yxVaYtLenSrz+0IQbbjk213PhPXJK+n8",
	"eaOFzR9VUTwPcfit5JOxWYh7FpLy7uEm8skIbJKMjpLRVLwl1AKHybobkhAOCCxp3bQ5ICdCOZNyCp9+",
	"Qd4UtS4YyLD9uESHc2iN8QsnDtISjYlzo7Q/EbP0sOc0dJBWpby5GMSQdm3mCQnEDEjiTcXroJ6XFqSP",
	"8jB16gOECUfuTzR/i2SYk+/ymP1TWxfhAAccwg5ZBFNlJ1fw6LgXME2S/MuD79TTj6/V048v1dOP3318",
	"/fHlx++efnz99OPLp4eDsVI9mBl5G3hnZybhxBz8Uw4LRxp+GvnscNqf3cPjb++O505/2hfE7Rt+l1un",
	"Y1mhcVjO7eBZau51w/7bluKnAIvREwJDGoukFiml2NNZCjpPaXfk3JmiRiY1i4UD1NBof+Gmuseo8/hS",
	"s2Aub4y7EFqImpeAfskIeYMYldiJ889BZBM3UxDjbxdHwCjI/cxycPTxLn4ZZphFIZd9ENvWQ24JyQ7I",
	"mIV7JedQbI3Tid12nuwiF/R39IWuyxDKmzeJEsWJfVQTYiXRxZaqqC2cdG2tFj8ldbAgoXAgTO2tWq68",
	"OCAZlCuXTZeGdq6RhM/owB/2sRkL6R8dE9DCP/wGRfRCespz+2P+7xH/9xWqgwWhfZWubyZuLatBTlb5",
	"fSijdA434UJV4lTo8JVKh0/jAd+ThOJZ1RyT7VTM7j42UnQASUE4KEZaGUsujYZkFNBPnfNG2XAGE9B4",
	"6C8dNDZwg1YQa4vamuDaa1kd7si+4SlGaXYXwehw/0YHxA8y6XlLgk0VoqMHKbgqHYuUmQDV1USW+Tdf",
	"pWPx1//4f4dT8Yohg2h1LyxABG50bW+pBXLfyY7VTZahKOUV6p6ug7GQRUGAAs445Zyb4XmhTQ4yR1kV",
	"jHp0A7cOQSZtHhQvAwAAPZlDMsv5QAVbPNFkx7PXNufpZ77rx7AvgXqSL3LeVLjaRuEQw8SouPLsgbWG",
	"fYVKeCiHPrgt796dPt/dmpfnl7z4l+9OnxP7BpioW+KJf+CEWxnrxQpuRGZy9K2S0bePjo6SEfLluXQE",
	"pV1ZUy9XSNOUbxQTn7ZeHHsGdq78gCYfmPGnW621jqBtRGksjNnSd+RtMNA/h2uVQRPTIJckBLpR55E3",
	"H1KTLtGVKVS2mcwlLq8FRl0rKdLm4zldlEaIbkMHdPqzldTLmIocCqI8pm+bwEgDySQ/ujHHb8kRH3yc",
	"5XA9a+2JGRoUXw4fzK05/8r40HmXGkTNZrwApqYgdYq7QO4JoUQauuARZAb5b9Al0T3CbKn8m6yoc3gL",
	"pbneiib2qgnIWqOtHr7CedSly03X3Foo61CRFchM9NdCOo9/vb8X4w6XZhEqO9BSfSAUUkZaVaCh/VhI",
	"sbRmzQb3ojDo1OnovNIl00SjOefqxULdoEndQDxZ1IW0Ql+A4aMu6A5wr5Tzh+x9onvdE0+K8U3uhKNm",
	"QtflHCwbbONYTSIdoBmYaEKOzDceBEGCyTgUl+rpb2C0D1WVDfl2L1Aq7yaVYfhrlGz9wrw3Z5c//fHs",
	"3ZvngxgLBnf372Bpjgd4gRL6zqnTM9uxdhexdT1PfWit3WKJXfdNoy+4jpmZmLZb8T3k/u/COZkT8ydk",
	"JtynDiIaa5+jSuy3qcPZoqbq1cN0smTt0odI/TqABIddqyZEHXEkDCeNyMIx+7Lo62QQvct3p+j6kE1W",
	"D4bqOojJ+9fPdJG/A2nXmOe4/4BsKw+mcK/qzzEMBwbvPxKr9qGRYlbnvz+rnRPb2YnucwIRunRtFzTE",
	"RmfVMCb7CYMUVCZ+UfkYtUNVyM0bWcInroQgXYsmTG5NlaN8L9CDdNMhuGi8dzg7mN/zkHQHGlrLeYvZ",
	"2iN9+iisbmaI4tVsc81y5SgRsbuSfna1lbhnFejvT9+cCaUj5gT0Uuk2fTuYrO0Tph3uVHsoRBx0sP5x",
	"C9LVuz8YTrs2xUq6Z4wKOt+LLv1hBcGrIShLQ7AcFkoDg6RXUueTAHBLRgvCGmhfbIgpklGz6LEI0CYe",
	"Mg2QpH/xtgaCJEZgnps5kJaQNVpY8LXVbSwAmUx5TguhkhDKOygWKKk2LpRgTZxCUyWghJQTi0Iu0Zho",
	"sIAhWxHr66QWK5UDfhOFYwj/s6/DftCGckYRetX198xiAeQEoucmc+HNclnAvpDmSroLtdRKL7+Dzb1p",
	"/sD1s/8UkF8AG6mh/Guppa8tiGuwaqGyAGefb2KtlFlQLZfSnJDAtVNE7KSTueEVB4cDDa7o6EmRVlew",
	"SQPt2K7gJ9GFj0VwYSLgMEKKOtc48RYKkA6EXEr0coSkQuVCXMGGKNigr4ijrGBWoJun4gf8kRm6qc5j",
	"eDsDkJoddSv2XOWG/N9ewZ9EB8tTLkJlOOqbMBI+9Qo2VPKqTfOZpoUeRI+DBthr336zSGsPtMIDPTEV",
	"6GulzWCc1SpjlQ/MEc7010dH4/1w13iLOFipJa6GTWPxL6Ii6JuNzlDDRFQrhfZXWRdeVUWQiIdTEcSI",
	"+ProqIMr6YSpai4Zbpe08r5yJ7OZrPyURpnSIqeZKWf7F3qXWOcHDci3O+T9cKlvAxm+l+7tqo+7FDCP",
	"fMukLoiJ34ILwnlXGYVdGfNJpux5g90zC+RXrjAluUiGPGfiOU3P0MeQlCUrTht0YNFvWpk1WnobOvU3",
	"4Og8b5q0sHgOcyX1xPlNsQdKH4B4dG7HYlJXXFCJB27iIKuJ7VytPLhEx3RosYkNChiC1tQAmNorDcUm",
	"1upJ32TJw4LdYJnJPm373JCceGbKstY4kxccPrgtsdLendPdk2zQd2iJsbtpp89j7qBLMsJFo7xIYxVE",
	"v6SqedzE+YCdGcIJuUErDFWehjXhW6+lKrjYma8eN4hJo6ET+pA9HpF5HpSFqT1BRClf9qRYo/KEn2tG",
	"A8bJux+P3k+bhXBQvVnK8T9PH04f3rKAAXPiRY+viY3HcUkUzhgLkNmKD8EWbVEtUZn2NWENA/+GNQjZ",
	"jNoCUWThTAgIUbS2HWwqzmzOGjtWrwi2ix84gZb0dUNYcp6kVc7oRB/wYUFF9/b89WFINnH814QRie3T",
	"hyd/mH5TPZw8CuUsj6Z/SBMd6vqLDWUzpL5yQ1f+c/orenYECRNxXHeJqoA3vW5gXx0ev6cAG2hy0i1P",
	"+jWz7snFAZfp5xrsZhiwa3wPSdcop6318gjx+k4h1S2L/X7fAURBvXPyUAzIVn5T2Jwi7Ioam4CjkOKu",
	"+9AXLttVlxNt5gVQZPMOGdHpkbTLc3fq3HszQr9OeNdoZRgQG4+y06vG2NjChg3GUm64loGARRxopQYO",
	"VIZCuY1SahREGdpPdTUV59z+gcqyus120jHdf3HxQniwJcGh4Rq0512QiQ5F4P06p229gmMNZdtLyBX7",
	"AnwNZykjrIqM7YKzLONo+XpjigeE+SdaJTqsISCmOtg3NIUZAiE+iqWFKhUzkRbGga8rMSlSsVLab8vc",
	"OHCkjVC4G04cPDw8SfREFMZUJxR9x78endDMucYUvwi5hpOYczCW0OS1zUDMa7dJtDMlNN852iyGbc1B",
	"rKDIHxNkTuWMBaIdf9BdhZhdSzvzZTVTmd/q2PSAduVBu8YHqGuaKlzkB4PsOFwFcaWGeghNmhp+2qlJ",
	"SCinDX46cEDYrYy8glDqlEOhrglAfWBsokUn98VoJ7hRHnJOocWyfyIJ/0xcbGs9RcqnYUd2ZxCReZr2",
	"vBlnXvsWRxfXjrMgcjrcm86WuX5Ke2jNo/Foaw53Q5CIqON4BoaOfQhn7UaEtDi7CN0vWF3j6hayVKHC",
	"pYs2ng6C5fdB0n99eGgPIPxu98K4gIseXPv33DtEGd0Ivf4qBuPt77Srq7CvZxecLQ+Vt6KD497bQq9P",
	"53+7OHvDzmeo0qgsKgbqDcOQ4J6ACDBGM9wZDdk2eJWRkzh6Px4FGOfdLBMaEsald0a9nYT7C+poCvc3",
	"HbZ3ZSjSipcMJ9IiXPXzPW5bodKzB7ImBAlZGA6dax8aMYbGjqfPLsUlyHKnamP0NDQZeHJ+2uSIqYpE",
	"hDSDFZfGFOLg9NnloVjDPGRDm3BOSLsRPPVJ51A23SIyWeFn163k6/RK+Ot//hfHR89PY+0RXVoKzyWu",
	"3eYFuI62Iuk//4u+YDXQIl/HW93+GPfA8o+7ZE0uUN+/QF3OxdaE5M1NVhP+PyQUg+ZCN8zWftWQ50+X",
	"l+ccv5NZiBS+NE13JsJdM3g39jISSofORloW1G5w5X01Y4hZW5NIqeHQ1CnRvb5FB+nSNFeK6WxnsPSw",
	"9dAuNxVc0BaHcFWcFE5jDfOZsxndSN9OvUsjLp2SzIl+Y3wIETQ9FKlxVM4ml3RCChIceMzYhEGLNHSt",
	"wN2YFGYZdiHRBymVRQdt/YvKP1FzxfSwmXGsmA7xh60bt8K2M/4Zb7cgdje0JUTDKbNEF2Y5oe57MxFB",
	"4E17PhejwHiBi3GFDY1P0ee1Vd5TaazOCzIhTO2b+tZOVSnP5jRufEpTiXwVXONEpx5u/IxMyUlYDFpn",
	"FGnkoOrMZB7aH5tmbnOTb3UYSzTtRBAnIUSofNGe+kCDpwEJ9OT8tOOgnYweTY+mR6TjKtCyUuGrR6Fb",
	"KQmwWdvGblBbvwVuGDaUaWX3e0Lu91S8BrsEF1EokxJKvIaHT/QBH3Tl2UXmxp3S1+6wddlL8HL6F2d0",
	"qKNzosK1OA5NMdJSHzjTTMDV9lpdU4CZzyghM6X1AWDWMPFpPjoZvVLOP43t7CLdaeXHR0dRuALD4bob",
	"hjPC79puuXcmfimMSIJ7t7tWh4KkAprUME1wiNCUekPF8+MozP89an0zmLS1arkEiyTRsA71AqHt3mWn",
	"Mpm6W6058dFt5SUOQre9RFOZ8WEozx1q2HeCEmXSadsXDden0qls4uW8ow0eh6JE1kkExRBb3WzQhh1u",
	"aINzCLpAeSHdhELmk26TwF5BFZdudeplIzSnm6ojgRj5O2YlTp+zMrAyuwoN8ZbUYe9aycZnbEXgEJ9R",
	"s0PaqNByGZx/avLN52WxppNb34wIbRC22Pv48z676Ss2wOJc89r0XONSWW5v9mk8+uoznjQGxAxM4TR0",
	"V4y8bmwIarM/m/WRBF//HlMKLTzJYGVUVCxjY7ZbG3vlKsmedYPd6IuH0ERTdw/1kGj4NB71NHKvMupO",
	"Ic812o0mdQFuxQqUtvPi6dnrwwAFDpLlnaPiAgamtrcGOD6d3k0jta1Zh2I0as/DcdCOUXer7H7SLGbc",
	"65P+4/DGtJfMYh/1T+9/Q+nfa/a9/3Q0i6Aj8dVvz39Pt6BcA4onbOYDt8MCv4rJZr+gY/JpdPLL9iUc",
	"eiAvblB1BYnmRDdGQTFSjQbFoiAMf0eXBZ3vqEAuvTh9efni7euUnIvmZD3Y7vMYMkvcTi9oLjvx6Ahx",
	"38YKLAFeYt/GRDeRl4NaU4yFYvWDATLH+hJu8GYybNDOFw8fHQVnBEQmC24u6TY6W1mjTe1OUK3ZcArT",
	"46Pj2JaVTKRet8nGBsZ5hdAltccUB2kTO00prphy+DQVatHpS8mxKaGNnjx8dHRI2Z02oBWKVvpa7oFj",
	"JY+6NeVAKS3nlMeNITLu4dGLj6FmDnWqaGXPO52vosVWa5donI01xjcZJi53NRWa3q7OjbhSRZFSdVWj",
	"7hvbmcCeqiiYdIme1z3sQYx9UjXPldL5ntBf6BIcfESjiw1ljcrK48lpYBExexduGwunQt60H0umgN/C",
	"FIVZD4k0btEZ7YTPJss+n6rf6iE6ZM52D2pU+Y977VeFNmvRaQP6dxN4+Nw//F7PDSUxkcvmgWnRdg3I",
	"FguS4DdS9E8xHVzlE72S1DaI3KkowehwqohVEgcyNhwhbVpZCOn1nhvUF/W8ZXhJCMLf24zI2/cU3GlE",
	"WKisyetMzVWh/GbWbcZPrUrBy1x62e+x8u70gUt0ZopCVk4h0ZJAz/BsgoRpCPmUfW8A2FPQf/ClkE1c",
	"QLx7++qQk0AV2ElrhM2oN3yiuecS9UJrMnMMGrq19f/QQX8Jvveih39Iw6U3w718HXngH8NseQldqyUw",
	"wrhtc0RBDt69eNM9+LwwywW/9GHgFzfwdQeijT+VHUD1vUIq5LHGu/AsSNQoyyKYCoS1KYpQVNpF7Aqz",
	"SHTTPfbiu3dt99izi0732FJWFb8dgN/v0Wsj5bhpLXI85TcC/Jbse0JUcKam6abBUbVQkYn+SgP15hrY",
	"HKwKcV6RSZdJSlpGcK9jzF6x2XNQGjT6b8jqzTMGGO6PdVE0ezHAbqT38ZphPHyHv5qnMIf1OkfeyRpt",
	"29NeS0bJgNM5xIaTUXJ2wxqJpt6oY9FH/45FhDu9GIu3ZxfiWPyb/PBhE697Zsqq9iDeco/8wzZ4rlx8",
	"jUJYbBTe7cs9WhgTQy8ZH0acNEaWaNbIUdNYokhY12C9VhS9a2E2p01haWNOUKfVluon/YezsRcqEDNf",
	"U7t+wug0nSij2dz2/Blsz0ndadoIdr9xpWg7Vya61zITvVm24SEXBKV0ftKAKwNIKbgfOOsOQDjRa9VF",
	"XHlFRm1oqRkCrE+0SI1Le62d2xo7AhKj3gvxrNgcnJDO2xWmKG/3udkd+OKArtppUO7jvlH5B1cnnl0w",
	"9skH/T9ugy+Ssr/dJVABPlgXmCb0U3E/vp+qnN4EIsn5aKTej++nSAVicpHGTuPUBuKsVMhVMebPiY4O",
	"UzE2CicewT0hiUYr3f82tN9S8W6DTweEUgerWyh+ecPvH7RCuU/g9Q7LD4YRGpTTkBDrCMimdKAnIGMq",
	"aK+IvIhAVtsBtTfPVLoRjT3BwNGqpboGHZh0mugLzraTeFuom4ZJm3hWrwV1yGDJ2puotZv2ybd1zyZB",
	"QS3CCN35cyrm1qxdsNM7GP0Ifu8UbfMz215MHNhIC1Uqn85S7lyRciFNFXp5h7pl9o9RzHbedjIUraZH",
	"nLflJbce+EB9Oj7iIJKGyt+ZiIfcDo3aotAyp3uO3M+9E1cq3RQFD+AI9lRBn12IXDluKovK5fS5CLov",
	"ioXD2w78/V+HON4j+OabXXbbiNPn/Bq6qqAiTB58aBY2yNj2wb+iz6jfUCaQQCG7E3wtb8L+u1Yi7iEG",
	"sVNvGk3lwPHRuNOF4uhoPICa3H70Gy4fMItW6ndm4q5UNQ7Hd8lvNxncIGLt4UndaxZU8EGkF9xvrTsJ",
	"4C7dXAHTO4T3LUnqnlLCL5FRyCd4Kp4MDB7eDGU0hBooMi9CuRByMCvyFQUX++3Y+H1KscfDzuP2qrVQ",
	"JzVMxT3VXb+Hsutjggc0z+vm/RZRLv3euSNjRakc+mFB2HXE4t9F/7aqoKVJPz0U9NO2/r2/zg3wi+DH",
	"tq+a6bxiajhyzzHCAK1p8T8H0Tcdi4vv3o0bDNtYnF2MO63sDoMHuvPelE6D4IOstpZP4l9qdJNj79LD",
	"2Jercao7wZ+BRscxhb1muDH7C8E52Gp6HBtU2lpzxQC93GVfu+DoDXU7BTdB/8G8d/DyPffebmbZddcV",
	"BcTa9/jELHQ0nqfiB5Yq3f7irPuDI0Kv71LUM0b6geby0WA4fXb5AAWQLWUR2nUfoH5lceHEl+2rXrKV",
	"VPpw3L4XjSo/tpo9h5nJpsk8hMhcJEXE1hB6o5RFsd25ff/LZDjS0IGUSd/IY3pvhRmkQVtSRBE7Gb1K",
	"3uXaQevzdtFRuNMTbhOufEDwNt3uux3ym+kZTeGUq4Am15vtlzxwIyu83lhpN2OxVF4tNYEeaG7cCD1P",
	"dHhf2Xa6Iy5tMLHAx/Wy7QDwW4AQtl8odx8YwtHnf3qAhu7H2nReOfqPiT/46vj4t5/S4AsmQnUFvVxK",
	"5rP4wsO/j37j08zlUHTkIkBiDxoiNMVvWp13lkW+ngPPHlRURx01GI9G1IOtqmtosFfXfd+8FlK20dv+",
	"yxJjgTIBbruw1vZNkd1AzYYpwOCKtiluW84mQyvnSvrVVDyV2VXQc1tuZ9JMLhmJee290SgKK+o1XDuw",
	"lFoX9LrTEAqGXHnXSJnY/59dVnprR2y7Cvk4AsbizI+PjuL8rhuoc3Q6D+L7p5sXaeKPJPbCCwwXdUEB",
	"7sMOuLSVu00WPsrsRNO8KYIWR6Qm15bRbE3fWnpzHYWgqamRHQulJ9RFOdELgBz1D2Nhzy7Fn19citPX",
	"569evH7x5vLFc9IecX1fHz0Ub84uf+r+3r7ksV0VIVBVJgqpcxdyyHhvX8YL5+s5l/1V0ob2kdx3mNDG",
	"J4nml67lUKg5cCGsqHUHYqr4lQosUVMxh8KskRwMBXYhAY8GQ96tkg8gAtKSuXJoXUhqfNTubud1331d",
	"EhnqMyiTPnT/V7191DdbfvcLi2ngYRD976eeBooXBuTf97unpnE+whuCD383pfVaFnjgoFVbc9zhv48u",
	"CLnp9oxtCf/IlhTM7mM994n55h3bQ2GtV9RIIodrKExFhQJ8begjwF0KTmYzSl6tjPMn3x59e0RI++uH",
	"lJgNz9xl6KE0kTjYk9D7UvSzcIetL99mrcZ73g+z/wWnEf26U6LRDt/Sanf886FsFCqrrdBo9IC6aql9",
	"wnnryu8BLdOYpdH4iC7IsTPNkLX99P7T/w8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
