//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ArtifactType.
const (
	Image ArtifactType = "image"
	Sbom  ArtifactType = "sbom"
)

// Valid indicates whether the value is a known member of the ArtifactType enum.
func (e ArtifactType) Valid() bool {
	switch e {
	case Image:
		return true
	case Sbom:
		return true
	default:
		return false
	}
}

// Defines values for BuildStatus.
const (
	BuildStatusCancelled  BuildStatus = "cancelled"
	BuildStatusCancelling BuildStatus = "cancelling"
	BuildStatusFailed     BuildStatus = "failed"
	BuildStatusNotStarted BuildStatus = "not-started"
	BuildStatusRunning    BuildStatus = "running"
	BuildStatusSuccess    BuildStatus = "success"
)

// Valid indicates whether the value is a known member of the BuildStatus enum.
func (e BuildStatus) Valid() bool {
	switch e {
	case BuildStatusCancelled:
		return true
	case BuildStatusCancelling:
		return true
	case BuildStatusFailed:
		return true
	case BuildStatusNotStarted:
		return true
	case BuildStatusRunning:
		return true
	case BuildStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for CancelAcceptedStatus.
const (
	CancelAcceptedStatusCancelling CancelAcceptedStatus = "cancelling"
)

// Valid indicates whether the value is a known member of the CancelAcceptedStatus enum.
func (e CancelAcceptedStatus) Valid() bool {
	switch e {
	case CancelAcceptedStatusCancelling:
		return true
	default:
		return false
	}
}

// Defines values for ResidualIssueKind.
const (
	CancellationFailure ResidualIssueKind = "cancellation-failure"
	CleanupFailure      ResidualIssueKind = "cleanup-failure"
)

// Valid indicates whether the value is a known member of the ResidualIssueKind enum.
func (e ResidualIssueKind) Valid() bool {
	switch e {
	case CancellationFailure:
		return true
	case CleanupFailure:
		return true
	default:
		return false
	}
}

// Defines values for ValidationIssueSeverity.
const (
	ValidationIssueSeverityError   ValidationIssueSeverity = "error"
	ValidationIssueSeverityWarning ValidationIssueSeverity = "warning"
)

// Valid indicates whether the value is a known member of the ValidationIssueSeverity enum.
func (e ValidationIssueSeverity) Valid() bool {
	switch e {
	case ValidationIssueSeverityError:
		return true
	case ValidationIssueSeverityWarning:
		return true
	default:
		return false
	}
}

// Artifact defines model for Artifact.
type Artifact struct {
	Name string `json:"name"`
	Path string `json:"path"`

	// Size Human-readable size, e.g. "1.13 GB"
	Size *string      `json:"size,omitempty"`
	Type ArtifactType `json:"type"`
}

// ArtifactType defines model for Artifact.Type.
type ArtifactType string

// ArtifactList defines model for ArtifactList.
type ArtifactList struct {
	Artifacts []Artifact `json:"artifacts"`
	BuildId   string     `json:"buildId"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`
}

// BuildAccepted defines model for BuildAccepted.
type BuildAccepted struct {
	BuildId string `json:"buildId"`

	// LogsUrl SSE endpoint for streaming logs
	LogsUrl string `json:"logsUrl"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`
}

// BuildDetails defines model for BuildDetails.
type BuildDetails struct {
	// Artifacts Partial outputs left on disk after a failed or cancelled build, so the
	// UI can point at their location.
	Artifacts *[]Artifact `json:"artifacts,omitempty"`
	BuildId   string      `json:"buildId"`
	CacheDir  string      `json:"cacheDir"`

	// Command The exact command that ran, for the troubleshoot panel
	Command string  `json:"command"`
	ErrMsg  *string `json:"errMsg,omitempty"`

	// HasLogFile A downloadable log file exists on disk
	HasLogFile bool `json:"hasLogFile"`

	// Residual Warning that a cancelled or failed build may have left the machine needing
	// manual cleanup. Present on `BuildDetails`, the SSE terminal event, and a
	// cancel response.
	Residual *ResidualIssue `json:"residual,omitempty"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`

	// Summary The human-readable summary shown in the Review panel and stored on the
	// build record for the Build Details panel.
	Summary  *ComposeSummary `json:"summary,omitempty"`
	Template string          `json:"template"`

	// TemplateUrl Download URL for the resolved template
	TemplateUrl string `json:"templateUrl"`
	WorkDir     string `json:"workDir"`
}

// BuildList defines model for BuildList.
type BuildList struct {
	Builds []HistoryItem `json:"builds"`

	// ServerTime Server time at response generation, used to correct client clock skew.
	ServerTime time.Time `json:"serverTime"`
}

// BuildRequest Start a build. Carries exactly one of `compose` or `yaml` — never a diff.
//
// Exactly one of the two properties must be present. That constraint is
// machine-checkable via minProperties/maxProperties rather than left as
// prose: a body with neither field, or with both, is invalid and the server
// rejects it with 400 `NO_MATCH`.
//
// `oneOf` would express this more idiomatically, but oapi-codegen turns a
// `oneOf` with sibling properties into a `json.RawMessage` union type with
// custom (un)marshalling and two empty `interface{}` branch aliases —
// generated noise around the hot request path, and oapi-codegen does not
// enforce the constraint at runtime either way. The property-count form
// validates identically for a two-property schema and keeps the generated
// struct a plain pair of optional fields.
type BuildRequest struct {
	// Compose The UI selections that identify one combination, plus any Advanced-mode
	// overrides. The backend uses vertical/sku/platform/os/imageType to look
	// up the matching pre-authored template in the manifest; imageName never
	// participates in that lookup — it is applied afterward, via a generated
	// extends delta over the matched template.
	Compose *ComposeRequest `json:"compose,omitempty"`

	// Yaml Complete template YAML (Advanced tab). Self-contained, not a delta.
	Yaml *string `json:"yaml,omitempty"`
}

// BuildStatus Build lifecycle state. `not-started` is the brief window after the build is
// accepted but before its process group exists (a cancel is already honoured
// there). `cancelling` lasts until the child finishes its own teardown.
type BuildStatus string

// CancelAccepted defines model for CancelAccepted.
type CancelAccepted struct {
	BuildId string `json:"buildId"`

	// Residual Warning that a cancelled or failed build may have left the machine needing
	// manual cleanup. Present on `BuildDetails`, the SSE terminal event, and a
	// cancel response.
	Residual *ResidualIssue       `json:"residual,omitempty"`
	Status   CancelAcceptedStatus `json:"status"`
}

// CancelAcceptedStatus defines model for CancelAccepted.Status.
type CancelAcceptedStatus string

// Combination Maps one valid UI selection to a pre-authored template file.
type Combination struct {
	ImageType string  `json:"imageType"`
	Os        string  `json:"os"`
	Platform  string  `json:"platform"`
	Sku       *string `json:"sku,omitempty"`

	// Template Filename in image-templates/. An empty string marks a planned combination whose template is not yet ready: the UI lists it but grays it out and refuses to compose/build it.
	Template string `json:"template"`
	Vertical string `json:"vertical"`
}

// ComposeRequest The UI selections that identify one combination, plus any Advanced-mode
// overrides. The backend uses vertical/sku/platform/os/imageType to look
// up the matching pre-authored template in the manifest; imageName never
// participates in that lookup — it is applied afterward, via a generated
// extends delta over the matched template.
type ComposeRequest struct {
	// ImageName Overrides the matched template's image.name. Omitted or empty means
	// "not overridden" — the matched template's own name is used.
	ImageName *string `json:"imageName,omitempty"`
	ImageType string  `json:"imageType"`
	Os        string  `json:"os"`
	Platform  string  `json:"platform"`
	Sku       *string `json:"sku,omitempty"`
	Vertical  string  `json:"vertical"`
}

// ComposeResponse defines model for ComposeResponse.
type ComposeResponse struct {
	// Summary The human-readable summary shown in the Review panel and stored on the
	// build record for the Build Details panel.
	Summary ComposeSummary `json:"summary"`

	// Template Resolved template filename
	Template string `json:"template"`

	// Yaml The resolved final template — what building this same request would
	// run. Identical to the matched template's own `resolve --full` output
	// when no overrides are set.
	Yaml string `json:"yaml"`
}

// ComposeSummary The human-readable summary shown in the Review panel and stored on the
// build record for the Build Details panel.
type ComposeSummary struct {
	Architecture string `json:"architecture"`

	// BaseImage Overlay-mode only — the baseline image packages are layered onto.
	BaseImage      *string `json:"baseImage,omitempty"`
	Description    string  `json:"description"`
	DiskSize       string  `json:"diskSize"`
	Hostname       string  `json:"hostname"`
	ImageName      string  `json:"imageName"`
	ImageType      string  `json:"imageType"`
	ImageVersion   string  `json:"imageVersion"`
	KernelVersion  string  `json:"kernelVersion"`
	Os             string  `json:"os"`
	PackageCount   int     `json:"packageCount"`
	PartitionCount int     `json:"partitionCount"`
	PartitionTable string  `json:"partitionTable"`
	Platform       string  `json:"platform"`
	Sku            string  `json:"sku"`
	Vertical       string  `json:"vertical"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// HistoryItem One row in the compose history list.
type HistoryItem struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`

	// Summary The human-readable summary shown in the Review panel and stored on the
	// build record for the Build Details panel.
	Summary  *ComposeSummary `json:"summary,omitempty"`
	Template string          `json:"template"`
}

// Manifest The complete configuration manifest, loaded once by the UI on startup.
type Manifest struct {
	Combinations []Combination `json:"combinations"`
	Platforms    []Option      `json:"platforms"`
	Skus         []Option      `json:"skus"`
	Targets      []Target      `json:"targets"`
	Verticals    []Option      `json:"verticals"`
}

// Option A generic {id, displayName} pair used for dropdown labels.
type Option struct {
	DisplayName string `json:"displayName"`
	Id          string `json:"id"`
}

// PackageRepo One repository the Advanced tab can enable/disable.
type PackageRepo struct {
	Description      *string `json:"description,omitempty"`
	DisplayName      string  `json:"displayName"`
	EnabledByDefault bool    `json:"enabledByDefault"`

	// HasCuratedPackages Whether this repository defines any hand-picked "frequently used" packages, i.e. whether `curated=true` on /packages/search can return anything for it. The list itself stays server-side; only this flag is published, so a client can hide a curation control that would yield nothing rather than offering a dead toggle.
	HasCuratedPackages *bool  `json:"hasCuratedPackages,omitempty"`
	Id                 string `json:"id"`

	// Priority Repository priority (higher number = preferred when packages exist in multiple repos). Default 500.
	Priority *int   `json:"priority,omitempty"`
	Url      string `json:"url"`
}

// PackageRepoList defines model for PackageRepoList.
type PackageRepoList struct {
	Repos []PackageRepo `json:"repos"`
}

// PackageSearchResult One package, with every version of it the search found. A package is
// reported once no matter how many indexes carry it — a Debian-style
// repository publishes the release, -updates and -security suites
// separately, so the same package routinely exists at several versions.
type PackageSearchResult struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`

	// Repository ID of the repository providing `version`.
	Repository string `json:"repository"`

	// Version The newest available version, and the one used when a package is
	// added without pinning. Always equal to `versions[0].version`.
	Version string `json:"version"`

	// Versions Every version found, newest first, each with the repository that
	// provides it — pinning a version therefore also selects a
	// repository. Ordering uses the target's native version comparison
	// (Debian or RPM), not string ordering, so `1:9.6p1-3ubuntu13.9`
	// correctly outranks `1:9.6p1-3ubuntu13.7`.
	Versions *[]PackageVersion `json:"versions,omitempty"`
}

// PackageSearchResults defines model for PackageSearchResults.
type PackageSearchResults struct {
	Packages []PackageSearchResult `json:"packages"`
	Query    string                `json:"query"`
	Total    int                   `json:"total"`
}

// PackageVersion One available version of a package, and where it comes from.
type PackageVersion struct {
	Repository string `json:"repository"`
	Version    string `json:"version"`
}

// ResidualIssue Warning that a cancelled or failed build may have left the machine needing
// manual cleanup. Present on `BuildDetails`, the SSE terminal event, and a
// cancel response.
type ResidualIssue struct {
	// Detail Remediation detail: the failing signal error, or the tool's residual
	// cleanup report including its `mount | grep` / `losetup -l` hint.
	Detail string `json:"detail"`

	// Kind - `cancellation-failure` — the cancel signal could not be delivered (or
	//   the build never exited), so teardown may never have run.
	// - `cleanup-failure` — the build ran its teardown but reported leftover
	//   mounts or loop devices.
	Kind ResidualIssueKind `json:"kind"`
}

// ResidualIssueKind - `cancellation-failure` — the cancel signal could not be delivered (or
//
//		the build never exited), so teardown may never have run.
//	  - `cleanup-failure` — the build ran its teardown but reported leftover
//	    mounts or loop devices.
type ResidualIssueKind string

// Target An OS option with its family and architecture.
type Target struct {
	Arch        string `json:"arch"`
	DisplayName string `json:"displayName"`
	Id          string `json:"id"`
	Os          string `json:"os"`
}

// ValidationIssue defines model for ValidationIssue.
type ValidationIssue struct {
	Message string `json:"message"`

	// Path JSON path to the problematic field
	Path     string                  `json:"path"`
	Severity ValidationIssueSeverity `json:"severity"`
}

// ValidationIssueSeverity defines model for ValidationIssue.Severity.
type ValidationIssueSeverity string

// ValidationResponse defines model for ValidationResponse.
type ValidationResponse struct {
	Errors   *[]ValidationIssue `json:"errors,omitempty"`
	Valid    bool               `json:"valid"`
	Warnings *[]ValidationIssue `json:"warnings,omitempty"`
}

// BuildId defines model for BuildId.
type BuildId = string

// ListPackageReposParams defines parameters for ListPackageRepos.
type ListPackageReposParams struct {
	// Os Filter repos by target OS compatibility, matching an OS the manifest
	// offers — a `targets[].id` or a `combinations[].os` (e.g. `ubuntu24`).
	// Omit to return every repository.
	Os *string `form:"os,omitempty" json:"os,omitempty"`
}

// SearchPackagesParams defines parameters for SearchPackages.
type SearchPackagesParams struct {
	// Q Search query (package name prefix). Omit to browse.
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Os Target OS distribution ID (e.g., ubuntu24)
	Os string `form:"os" json:"os"`

	// Repos Filter by enabled repository IDs
	Repos *[]string `form:"repos,omitempty" json:"repos,omitempty"`

	// Limit Max results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of matching results to skip, for paging
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Curated When true, narrow results to each matched repository's hand-picked "frequently used" packages instead of its full catalog. A matched repository with none defined then contributes nothing, rather than falling back to its full catalog.
	Curated *bool `form:"curated,omitempty" json:"curated,omitempty"`
}

// ValidateTemplateJSONBody defines parameters for ValidateTemplate.
type ValidateTemplateJSONBody struct {
	// Yaml Complete template YAML to validate
	Yaml string `json:"yaml"`
}

// StartBuildJSONRequestBody defines body for StartBuild for application/json ContentType.
type StartBuildJSONRequestBody = BuildRequest

// ComposeTemplateJSONRequestBody defines body for ComposeTemplate for application/json ContentType.
type ComposeTemplateJSONRequestBody = ComposeRequest

// ValidateTemplateJSONRequestBody defines body for ValidateTemplate for application/json ContentType.
type ValidateTemplateJSONRequestBody ValidateTemplateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List the compose history
	// (GET /builds)
	ListBuilds(w http.ResponseWriter, r *http.Request)
	// Start an image build
	// (POST /builds)
	StartBuild(w http.ResponseWriter, r *http.Request)
	// List a build's output artifacts
	// (GET /builds/{id}/artifacts)
	ListBuildArtifacts(w http.ResponseWriter, r *http.Request, id BuildId)
	// Cancel a running build
	// (POST /builds/{id}/cancel)
	CancelBuild(w http.ResponseWriter, r *http.Request, id BuildId)
	// Get a build's command, resolved paths, and summary
	// (GET /builds/{id}/details)
	GetBuildDetails(w http.ResponseWriter, r *http.Request, id BuildId)
	// Get the full configuration manifest
	// (GET /manifest)
	GetManifest(w http.ResponseWriter, r *http.Request)
	// List available package repositories
	// (GET /package-repos)
	ListPackageRepos(w http.ResponseWriter, r *http.Request, params ListPackageReposParams)
	// Search available packages
	// (GET /packages/search)
	SearchPackages(w http.ResponseWriter, r *http.Request, params SearchPackagesParams)
	// Resolve the base template for a set of selections
	// (POST /templates/compose)
	ComposeTemplate(w http.ResponseWriter, r *http.Request)
	// Validate an edited template
	// (POST /templates/validate)
	ValidateTemplate(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBuilds operation middleware
func (siw *ServerInterfaceWrapper) ListBuilds(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuilds(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartBuild operation middleware
func (siw *ServerInterfaceWrapper) StartBuild(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartBuild(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBuildArtifacts operation middleware
func (siw *ServerInterfaceWrapper) ListBuildArtifacts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuildArtifacts(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelBuild operation middleware
func (siw *ServerInterfaceWrapper) CancelBuild(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelBuild(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBuildDetails operation middleware
func (siw *ServerInterfaceWrapper) GetBuildDetails(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBuildDetails(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetManifest operation middleware
func (siw *ServerInterfaceWrapper) GetManifest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetManifest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPackageRepos operation middleware
func (siw *ServerInterfaceWrapper) ListPackageRepos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPackageReposParams

	// ------------- Optional query parameter "os" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "os", r.URL.Query(), &params.Os, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "os"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "os", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPackageRepos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPackages operation middleware
func (siw *ServerInterfaceWrapper) SearchPackages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPackagesParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Required query parameter "os" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "os", r.URL.Query(), &params.Os, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "os"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "os", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "repos" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "repos", r.URL.Query(), &params.Repos, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "repos"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repos", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "curated" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "curated", r.URL.Query(), &params.Curated, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "curated"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "curated", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPackages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ComposeTemplate operation middleware
func (siw *ServerInterfaceWrapper) ComposeTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ComposeTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateTemplate operation middleware
func (siw *ServerInterfaceWrapper) ValidateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds", wrapper.ListBuilds)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/builds", wrapper.StartBuild)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds/{id}/artifacts", wrapper.ListBuildArtifacts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/builds/{id}/cancel", wrapper.CancelBuild)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds/{id}/details", wrapper.GetBuildDetails)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/manifest", wrapper.GetManifest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/package-repos", wrapper.ListPackageRepos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/packages/search", wrapper.SearchPackages)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/templates/compose", wrapper.ComposeTemplate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/templates/validate", wrapper.ValidateTemplate)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zH39chtHkuerZOA2QuRNA6Akj3dMx8YF9TE2dyVRIVKe2FPr3IXuBFBmd1W7qpoQrFPE/bUPsHFPuE9y",
	"kVlV/QE0SHpOkucvi+ju+sjK7/xl+eMk11WtFSpnJ6cfJ7UwokKHhv960siyOC/onwXa3MjaSa0mp/4B",
	"yAKVk0uJBo7evj1/djxJJpIe18KtJ8lEiQonpxNZTJKJwV8babCYnDrTYDKx+RorQSO7bU1vWWekWk0+",
	"ffoUH/ISzoyTS5E7XpzRNRonkZ/40T9O8IOo6pKGaBaNcs2jb6ZGL7STuZ2KysyM2MxWv02S3YkSv8z9",
	"FSQTK3/D/U3/2FRCTQ2KQixKBHopAZytZpBOHs4ePoYfnqSTSdJbUPh1bG7/w8cJqqaanL6byEqscJJM",
	"7EJXk/d7H3zqU/Cd33t4Keyj+0YvfsHc0SSReC+kHSGgCE/5D+mw4n/8k8Hl5HTy3+YdY8zDeczbw2g3",
	"MBHGiC39veh4ZZ+eTrjmztGZqS79q7sbjqO3YyW95Y9tnQc7y3OsHRb7e79ttaVe2bem3GeAy8vngKqo",
	"tVQOltqAdQZFJdUK6JvB0c9FLec3D+c8kZ2LRT59+OjxPLz3dSgUN3KQPs/QCVnaO1hjSITX9EyUoBtX",
	"N85CiUsHWkEh7TWIpUMDApZClliANpALlWNJf/ACE7Aa3BpT9facnoEnpnD0ozRQ6lzQRLNUkTL5kkyZ",
	"i3yNz6QZf6irSqgRzXe1RsAPIncQXgG3Fg6MUAmzhFsjOKObRYl2rbWDWigsx44cjXlpV6Ozr4V9oVd/",
	"leWIFjqDQm9UqYMWKvUKlrKkRUnrbDyJbsKF1iUKNWF2sbJoRHkXRd+E986tbfDv5M5kYpuqEmZ711dP",
	"6SeLl+FtOkSs6lI4HCVNfDgqoM8CZeDtmxftaRi0urzBAtpxRw5jo831OC/cLWaRV3orH66zG77HdYNT",
	"Piih45rbK5V7q+0fpXXabM8dVmNCYtHcoLmS1Qi3XfIzcLJCElKDttbKIqxQoWFJTaCxRFwNuTYGSTBK",
	"iYr+o/NrsNe4mU2SyVKbSrjJ6aQQDqc03iS5D6mJwL0FHiTUG/y1QU+rnR04YRwIr35m8FQYI9F6GS63",
	"oBWCXkKWezbMSGdlW1GVGfzX//m/oPCGFVohl8tZqlL1fPgdi/tGQ3c+UDXWwQKhNmhRuRlckYLItbLO",
	"CFJ20qaqEvlaKpzma8yvWZBvpIBKqtftQPNKfOj+AiPcmk5iLZTXucKmqjba4intThdb2Ei3BoWSX1xK",
	"JHWrjf95od06AWlBqhtRygK86kLwxE2VQaKnBen8B9+cnED26uLnl2dXT3/MeO+ZVnixzGCjm7IA/EA7",
	"tODW0kKlDYIspK6Ek7koy20Ci8aBFrWc5rrAFSpwjVEWRG8gmsjKRUkmtEdCqZwGAdkvVqvZG7F5idaK",
	"FWbQKKkVEAfwt6nKG+t0BUeNOq6EsWtR8li8uY0GrGq3hUwqh2Ypcvz4KYOFESpfgyilsGjplFMV2BkL",
	"UFpaBGF0E+iz1sT2zFxAjlbCgw/2VWi0oLRLFaqlNjnyh70TJ8lpFAtROJ2N2BJjYNz1dprrxnsVVepP",
	"SDiiBLvYTFBWaIK2NY0fgZdwXtE1Ym154nYzKS2gyYn761JIBbWQhrhWs3CI0jOJ9cZ2wG6T04fJZMCO",
	"/MtQDQWZuaeGjxL6KZmQfO1LKr1XosNWUcO/n718AUdnxQ05EQU4sTiewSWWy2mulRNSYZEQ4UlAsXRi",
	"NqpTxhXGZWvTxkKbUi4x3+bk5jvhcAaZ0m5qSZdgkZEcEaUXRuISNlIVehN8H/7ZR0c2VSI4oCwLC1yy",
	"lDhLp56T7KyMbupouo9E8JZoeFFSoLGFtVa6MXSWxDd4PIMsuFRSrTIoBX1JvFV6plvT1EuppF0T+5BH",
	"sFHgUBhyG/xJx5ijtyWK0BqliGRko+IE3R/8im1yWjapc3bwRgKVZPKUP/j7XO/P4KHEzfU28T75vUZ9",
	"zMw81dVCKuHZZJdrXorask3wyvXtOVgsMXesrkiX1QanonFrbXqeCHtuxLRDCnEseBUCxD0aaTv6Mw1I",
	"2mM8ALtubvWm9jdEbglFmSAV8Hqm8V07n8GZCqrVDwWVMNfWqxmlsCDfONIKNmttezItWVXCFkmtimJ7",
	"ynz79hxKFgLpWFZWRmz5D904Vm8Glw2pa/YzWJ/Mg5i52SDwapMAH/7y7c/f9nIBv4jffttOpdWzbTXq",
	"kN/QCeSe+W7nl/bNHtn5YJLe2fWoe4Cd+lpxNNDos5H1gUbIuXgHpEfmBOqysSDUFqK+nFa6wFTpGzRG",
	"Fmi9wVmI/BpVAUzNuJG5vW7mcStzbeftNojgpdbXqWpqPqlKOHJdVgc4WqrwlpJLtO57zzyviJPYl0pV",
	"TQFkLmtv35TfFk3R1OxyScf6r65LiYXXqhthioQ9JNG3bvjBoSqs1/2gb4L65RX21uSV3oiIvRJjLu9F",
	"pNfoYA+s39GMhGMGF5V0zke6XiAqFMqmKiXlCoH0Bap0wns7MCKpaC9slr3p1iC/QLVy68npt99wlseh",
	"oRX+r3di+tvZ9H+eTL97f9T9O02nP7//771nx//jn8b4/Oupl88sUbeKkQ9M9s3NZwlDhxzyZjeiZD3e",
	"z8n1iTDu7Fz1I9OlJGesHY04ZUNSwRqOZI19bEscEl1R9sFTZRo1g/PoJJKw3sJiWZgQptNlU5ZZyOGk",
	"arNGBUpDqypAGIoMnGfE24+uF/TyVrvI/5bzuuxOZZ8u651Eq38X7Jo2ERTMG7yRuPHZFTYQFOKSICqf",
	"XvLGwWCuTdGmArxvF7Je/tsx5SBMvpYOc9eYcRlZCIvnnLAd1R6l2LLuBa3KbSv39FEpFXr9AbXIr8Uq",
	"kLoUW/Srd3o2xkSDSUZWVEh7fRmy1vvpJG1dzJaPa4NXtz49qCv46U9o7KFlXaNRWN72xiF146nzlIKi",
	"3gsUyK3Q+DeMk0SP+7xzRYz0B+s1Gux2f6E7ih3SDs8/GTLoLpV3iNfjjT2i7VGoxytjwvvcGG32VSyO",
	"/0zh8bBA8+ri6ue/Xrx99WyMxSsf5A+/8GJMtnRJEfmdyojn7Mba38TO+37pY3vtJ832pVwhGL2Jyih4",
	"pLD237Aru+/W5wbJbzljZr1PPiyZyM9WT/ky+dgdaspBXrRnGLqtj5H6ZXAWx61BHtMCuVZLuWp82rH1",
	"MBMotShYd+YIi20MJ7QCjm2bekzF9zzn++dR+xHgSB41ivb9B7yoD41lr5vPMYwTZoW/o8B3xe+PjRQV",
	"2f//qvYktncS/XkCEfp07TY0xkYX9XhsfuZjBpnDR1kkUEhbl2JLevaTz4hxApt8hMLouiAnoxQLLO2+",
	"CPe+HTeIxT2FpD/Q2F5eexX+Bmt9QPtgra1kbUMM38+RcV0NFSn0eSEt/XdkJ0OHotO4FzWqn85fXYBU",
	"SzRIQoVqRX5L9FhG/ZMhYbrhzpXDEuKgo3UwXmnxZPsMl6Ip3eD7pSgtjtWy1sI+bTgOfB2XtUenv60x",
	"5Myl7ROswKVU6IPltVDFtJb5NRaQTpbsXitXbpkp0km76QTkDGewCUNmuZ/8X5xpMCNlM49vzi2SfeZT",
	"MOgao2gixzEzMZl0PhAnIwHSWSyXpKm2NqTip1YW+L33HXnly1KsKDKsm0Up7Rp9EVW0dRahYC0LpF+i",
	"csy1ckaXPrb26fqtRG9JeSH9aoJeLpGzOAIKFAU4vVqVOHD9e4T3LN4dMLlb5VTXqG6k0qMwCyO1kS44",
	"++GM/3xykuyFVe0JxU/gaC1XtFDVVAs08C9QG1yiIV+Zg5bWi+YcKtnjqimdrMsgIcczCGwFfz456bnW",
	"PS+x8aXEbktr52p7Op+L2s14lBlvcpbran54o3eJuZ9ohN/vkP/xEiCv6966uK9O7lLIfuRbFnXJ/P0G",
	"bRDWfeUUTiXxBR68QbOFG++egl6CdKHyxHLCjt0MzuJXnDinRRgXrbrSFNI6NLDWG7L8W5CqwA9oIRfG",
	"bGlECrMEPMOFFGpq3bZEP0rkqCA8NtSESxQWE5g2tS+0UAg5tZg3zHa2kQ5tqizWguS83Ebggo/C41KN",
	"bpxUWG5jDl84sLRfUcYN2zH346D2fabzazTwVFdVo2glzwsZnP49udoHQBX89TQf9SU7Yuwf2vmzWMzs",
	"k8zoG8nphyzsJRumWtvpptaF8GEsVLKjVplUoMINWgfiRsjSF0H920lbndQKvXlmaRcDHhEFuX3EYrpx",
	"UEsuX8zgrNyQMsVfG58QiYu3707ez9qN+EJIu5VH/zx7OHt4ywZGzMvzAV8zGydxS0tpyDVFka+9EOzQ",
	"lhQzl29vON0S+DfsAUQ7Khd9uGwkSqtDNphrqN1gM7gwhdfgPkW+RvB+0gML5FndtIRlZ1oYabVK1ZEX",
	"FtAG3rx+eewraSGhr8OIzPbZw9PvZt/WD6ePfXL94ePZd1mqQr2/3IJunBHq2o69+c/Z78DyBA0TQ9m7",
	"VFVIud20kW+Px++pwEbAT3XPofg9qx7oxREX+tcGveztl2G0GyQTWuO0s18/Qnw/6VZ6y2Z/OiSApKj3",
	"JI/UgOj0N4nhhliQODTXFVpYGl3tu5ND5bJbjZkqvShxuhD2Lh3Rw07u89ydNvfejDCsH+47jsIon3YV",
	"DkQPw6ZNhLb5xEQlyIO8QY/I8KlXBnaAQiTVmapKKFJEOflPTT2D1x4WQi5j1gfhZQl/f3n5HByaijPC",
	"eIPK+VMQqQrF4YjBGbcrNNZYxrrCQnrf0L/jy260GdqolSuezxhtGDPCOkTr8gE5zp5WqQp7AG+cQaq8",
	"bNg+SGchqxjA8L9hZbDOYA5ZqS26poZpmcFaKrerc+PAkTYg6TQsHD08Pk3VFEqt69N5gTdz+tfjU165",
	"rz3RD1DgjczxNPyXVm3Q6sbkCIvGblNldYXtb5YPyzpZlrBAWGNZfM8YDVmggVD8hgf9XcD8Rpi5q+q5",
	"zN0OkvMBn8qDbo8PyNa01TniB03smI6a7ms5hi2ctrV9PqkpnU5jMGtTyIEDwmnl7NeT0l4gFFjKG84h",
	"H2mTKugBETyGCT9Ih8Wx92MCHIBJ4h8zF5tGzYjyWTiR/RWEtLpQfObtOIvGQeuyxb3TKpicls6md2R2",
	"CEMY2/Mkmeys4e4qPhM1iTIwJvYhvbGfIVBwcRlQMd5c0+6WopLl1ktfL+E6G60XHMrK//50wYGc+N3h",
	"hbYhNTy69588pkhq1Sq94S5G869vlW3qcK4Xlx70zD4IFtBLZR+E1g/p/K+XF68YRBULVbUhw8CYMY9F",
	"GigI78TM9Dhimtg2RJWRk3w2N5lsvP6+m2VCo0Lcem/U20l4uNzIS7i/67B7KmOZN3qlxxC9WDzs8zNO",
	"t2tQee6RLDoxr1pqn0pVLjRohIaP86dXcIWi2itcTZ4E8MHZ6/O2KMeFNAhpZwNXWpdwdP706hg2uGCf",
	"oVdoZf2DhuGIZz2hbFEkuajpb+8FNxbNA9vHUPzXf/ynz5e9Po/lV361AqdTtQPToX10Rdn/+E/+wZsB",
	"HoRrNMlOFwADLMDrP4+enV6SvX9Ottzywq/W0kKh86ZChoP6uNJbLgrDTOPWLXl+vLp67fM5Ig+Zox90",
	"i9qkc/HBa4txBKkC4lGJktsQ1s7V84wLjR3Qkfy4CPZM1QDPeJStdPsmzOZ7g2XHXYR2ta3xko84JKTi",
	"omgZG1zMrcn5Q/515mwGlSQhAemYGq+0CymCtreCAaWFd7mEBQGsOEjMvAtDHmlAs9BpTEu9CqeQqqPs",
	"h+dXEK31R1l84qaL7LhdcfBupyH/sPPhThpv7h/T5wZh/0A7QrScMk9VqVdTRuXPIbZStLB9G7OC9IKN",
	"eYUtj8/ZyI2RzqHiP0p2IXTjyE0Zojsh86s5jwef8VIiX4XQOFWZww9uzq7kNGyGvDMG2Phmi7nOHXYP",
	"W5D3Qhc7yONU8UkEdRJShNKVndQHGjzxckpy1gvQTiePZyezE7ZxNSpRy/DT49DFxAps3sHbR631G/RA",
	"4rHKmw+/pxx+z+AlmhVaIM8IpJpWWNE7fvhUHXlBl86HyL6hR7jGHnche4VOzH6xWgUogYWa9mJ9aopb",
	"LVJ1ZHW7ANuYG0lKRQQZJXI6Ydyxp1bLxOfF5HTyQlr3JMLcI915549OTqJyRV/e7h8YrYjBLW0X3Z2F",
	"QE4jsuLeR932KMgmoC0V8gLHCM2lGDI87yZh/e/J6uvRIp6RqxUaIonCTYA/BDi+h8F4SAujXjc+Ed6H",
	"+MJRQOGnipFeXpLzUSD/KWmUaQ/OHx3XJ8LKfOrEomcNvg+4DG+TSq2vLeyg3MiHHQe60RqCLZAOhJ1K",
	"633nrnnA9auXWJD/3YMMkf7dLd2wQoz8HXoW4PyZNwZG5NcBKL9i5P2NFG3M2KnAMT7jJgg+qNCKidY9",
	"0cX287JYi/AeuhHONPhpj70ffd65W7zxCIt72E+LxfZoIQ97/pRMvvmMkuYBEiNLOA9dF5HXtQlJbR/P",
	"5sPK8p+/xpJCaw87rMAFep/yiEHeRptrWwsfWbe1/KF6CM01qi/UY6rhUzIZWORBf+GdSt7D1FpLauHI",
	"T8cGlI/z8snFy+PQIBE0y1vyGxdbxs33PuVEtTfai22rtY3eBHwtWeGQB+05dbfq7rN2M8mgf/rd+MF0",
	"r8xjf/Wn919Q+w+agA9LR7sJFolvvjz/PdmB9owYnnCYD+weC/wuJpt/pMDk0+T04+4rPvXAUdyo6Qoa",
	"zUI/R8E5UkUOxbKUq7Xr27Jg8y3jkrPL8x+unr95mXFw0UrWg93+j1BZ8jD7YLnM1FEg5Ps5ajQMgIj9",
	"HKlqMy9HjeIcC+fqRxNk1ttL/EAfs2NDfj48fHwSghGEXJS+6cRuVb42WunGnpJZM0EKs0cnj2K7FrtI",
	"gy6U1gemdYXUJbfNwFHW5k4zzitmPn2agVz2+lV8bgqUVtOHj0+OubrTJbR8GWTHyj2w3siTbc18opS3",
	"c+7HjSkyofbyY2SZK006eEle9gJz0Vjs9cKBaZRNFa3GaO3aChO/keuaXG/bFBquZVlmYJoSW3Pf+s7S",
	"hlwjky5Vi8a1LotgJC7nPjNipmupigOpv9A9GGJErcotV42q2pHkyGWQyVi9C58lYGWomw5zyZzwW+qy",
	"1JsxleZbd6Kf8Nl02ecz9Tu9RWPubF9Qo8n/ftCWBUpvoNce9IcpPJr3u681b+i7iVy2CExLvmtoNTMo",
	"GDUuYCjFLLjSpWotaAwfTkUNxsIpI3YFjkTEXLM1rQ2G8vogDBqqen9k9EpIwt/bjSi6+wvudCIM1kYX",
	"TS4XspRuO+836XMLEzpRCCeGMPO35w9sqnJdlqK2koiWBnqGuRkipDDUUw7dDMC6ca8RHY7+BKLNC8Db",
	"Ny+OfRGoRjPtnLA594ynqpAGc6dJhbSVOY7Mxa1XAowJ+g/oBhdA/EM6LoMVHuTryAP/GG7LD9j3WgIj",
	"JF2nByc5/OnFj+7B56VeLf1lECNP7MjPPcguPap6ANt7pVQ4Yo1fkSwIsiirMrgKjLUpy9Ds2Edwgl6m",
	"qu0qu/y3t11X2cVlr6usEnXtbw3w934MOmmsb2Yjjuf6RoBjsn/PiApfqfEe19tz8Fk1VkMMF+qgv0Ro",
	"ciWMDHleyIXNBRctI9jT8qUjZbk9ICgtOvkLsno7xwjD/bUpy/YsRtiN7T69M46P7vFXO4vnsJgHbaFk",
	"t7JGC3mKlXWJIWTKBXlRAXFaRM3ZT2uk6ghnq1kCQzRoAhHu9DyBNxeX8Aj+Vfz22za+91RXdeMQ3vje",
	"+eMueS5tvF4hbDYq7+7Sjw7GJHkOjw9jTkqIJdo9+qxpAAl67GPwXmvO3nUwm3MXrWjrTpBt6FH9dDi5",
	"d/YWIf3gGm7jZ4xOrqsuBURuc9uoldUdVi8OksGCL9NoM9hopheXAaCFJpy8Ddmj/uQGgw+PBTCU0rpp",
	"C64MIKUQftCqe4DRVG1kH3HlJDu1pc99hgTrmYJM22zQ8tleh+CBpWT3Qj4rNg0z8rWPQKUnpG8Phdk9",
	"+OKIrdprXHbx3LgdgIuIcHHpsU8u2P+kS74Irv72t5AqXroNTJMF1Pm79zNZ8A0hgoOPVuu9ez8jKjCT",
	"QxY7kDNi2ItKElfFnL8vdPSYymOjaOER3BOKaLzTw7ekfUnDuws+HVFKPaxuKf2lDl8/aUV6n8HMPZYf",
	"TSO0KKcxJdZTkC2UfKAgYynooIq8jEBW0+vqa+eUqlWNA8Xgs1UreYMqMOksVZe+2s7qbSk/tEza5rP6",
	"FayIoBWN09Fqp2pE/z6wELcG1mHNioJblxnd+WsGC6M3Nvjp8WTJgRFOkDsplXUoCgoz/Zwe9eMvT6HZ",
	"slJW0mXzTC+XFl3mGytqntGtjW5WEQJpSc32bkEZy1bzFK+7doNbBT5Qn8UHjiJpuJ3aE/HYt2mTFPpt",
	"zg6I3K8Diaukiu3Xj0ZwBHtVjlbPFJLeWjRsXM6fQbB9US0c3ybw978mMTmg+BbbfXbbwvkzfz1dXXJT",
	"nh98bBUm6Nhu4hZYcOAOw17TkttyJZBBIfsLfCk+hPO3nUY8QAxmp8Ey2s6BRyfcGi+rppqcPjw5SUZQ",
	"k7tTv/LtA3rZaf3eSuy1rJMgvit/68noATFrjy/qXqv425pEnUgPShijN/1FsGMbG7cHQnjfFpW+lDJ+",
	"iZ1CL8EzOBsZPNwYpRWGnhh2L0L7CHGwN+RrTi72DfYy3LPEWAen96c7aNZC38w4FQ90+3wNYzfEBI9Y",
	"npftvRdRL33t2pE2UElLcVhQdj21+IfY384UdDQZloeCfdq1v/e3uQF+EeLY7gqa3tVT45l7nyMM0JoO",
	"/3MUY9MELv/tbdJi2BK4uExCFYvY7zhEoHv3qfTuSDjKG2O8JP7SUJgc27cDOsZ0QXUv+TNy10MsYW88",
	"3NjHCyE42Ln3IVW+m8s0yncM8KUvh25MiNFQ/7KENuk/WvcOUb5DOyhW98N1yQmx7n6fWIWOzvMM/ua1",
	"SkeqJNj+EIjwtV40DEcb7SRdfiw4DOdPrx6QAjKVKKFCs0I4Ivvq1YWFP3VXwORrIdVx0t2Xxp0fO/dd",
	"hJUJ1a4sZOYiKSK2htEblShLyMIE2V2XzPhMQw9SJlyrj+mg2iBrSIOupYgzdiJGlf6UG0Z5h5i3j46i",
	"k55qVW65SuPhEZUu5FLGNIdXs93ytOJ0ynVAk6ttD0jktyYtZ36rWhthtgmspJMrxaAHXpvBSt9gkapw",
	"j9luuSNubbSw4MX1qusI/xIghN2L5u4DQzj5/LMHaOhhrE3vKtJ/TPzBN48effklXY1JUeiu4EunRDGP",
	"FyH+MfbNS7Nvh2KRiwCJA2iIcC9Qe9tLb1sc61l0PoKK5qhnBqNoRDvYmbqWBgdt3U/tdZGiy94OL1EU",
	"K0HayANu+7DW7gbJfqJm6yngwRURZdxvZxMers357Bk8Efl1sHM7YWfaLi6dwKJxTitShbXeIPfdGy6t",
	"A1+DGlLBWEhnWy0Tr0DyIavKESRt0CMckwgYiyt/dHIS13fTQp1j0HkU76VuL9ikh6z2wsWGy6bkBPdx",
	"D1za6d22Ch91dqp43ZxBiyOqlc+N0bjtNZt8ox2noJfCOjQJSDWtS5FjqpaIBdkfj4W9uIJ/f34F5y9f",
	"v3j+8vmrq+fP2HrE/f355CG8urj6uf+8u/yx2xUjUGUOpVCFDTVk+nao48G6ZuHb/mphnC8iS9uijU9T",
	"5S9jK7CUC/SNsNCoHsRU+lulvEbNYIGl3hA5PBTYhgI8OQwFtkwoIoiArWQhLXkXwnAxsT3d3jXgQ1sS",
	"GeozGJMhdP933Urq2iO/+yJjHngcRP/1zNNI88KI/vtpX2ra4CPcHHz81YzWS1GSwGFnthZ0wn+MLQi1",
	"6U7GdpR/ZEtOZg+xnofUfHv39lha64UmL7bAGyx1zY0C/t1wj4C/peB0Pufi1Vpbd/qXk7+chP/tABdm",
	"w5z7DD1WJoKjAwW9P8GwCnfcxfJd1So5cEXe4YtPI/p1r0WjG76j1f74r8eqUWSsdlKjMQLqm6Vuhtdd",
	"KH8AtMxjVlrRFH2QY2+ZoWr76f2n/xcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
