//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ArtifactType.
const (
	Image ArtifactType = "image"
	Sbom  ArtifactType = "sbom"
)

// Valid indicates whether the value is a known member of the ArtifactType enum.
func (e ArtifactType) Valid() bool {
	switch e {
	case Image:
		return true
	case Sbom:
		return true
	default:
		return false
	}
}

// Defines values for BuildStatus.
const (
	BuildStatusCancelled  BuildStatus = "cancelled"
	BuildStatusCancelling BuildStatus = "cancelling"
	BuildStatusFailed     BuildStatus = "failed"
	BuildStatusNotStarted BuildStatus = "not-started"
	BuildStatusRunning    BuildStatus = "running"
	BuildStatusSuccess    BuildStatus = "success"
)

// Valid indicates whether the value is a known member of the BuildStatus enum.
func (e BuildStatus) Valid() bool {
	switch e {
	case BuildStatusCancelled:
		return true
	case BuildStatusCancelling:
		return true
	case BuildStatusFailed:
		return true
	case BuildStatusNotStarted:
		return true
	case BuildStatusRunning:
		return true
	case BuildStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for CancelAcceptedStatus.
const (
	CancelAcceptedStatusCancelling CancelAcceptedStatus = "cancelling"
)

// Valid indicates whether the value is a known member of the CancelAcceptedStatus enum.
func (e CancelAcceptedStatus) Valid() bool {
	switch e {
	case CancelAcceptedStatusCancelling:
		return true
	default:
		return false
	}
}

// Defines values for ResidualIssueKind.
const (
	CancellationFailure ResidualIssueKind = "cancellation-failure"
	CleanupFailure      ResidualIssueKind = "cleanup-failure"
)

// Valid indicates whether the value is a known member of the ResidualIssueKind enum.
func (e ResidualIssueKind) Valid() bool {
	switch e {
	case CancellationFailure:
		return true
	case CleanupFailure:
		return true
	default:
		return false
	}
}

// Defines values for ValidationIssueSeverity.
const (
	ValidationIssueSeverityError   ValidationIssueSeverity = "error"
	ValidationIssueSeverityWarning ValidationIssueSeverity = "warning"
)

// Valid indicates whether the value is a known member of the ValidationIssueSeverity enum.
func (e ValidationIssueSeverity) Valid() bool {
	switch e {
	case ValidationIssueSeverityError:
		return true
	case ValidationIssueSeverityWarning:
		return true
	default:
		return false
	}
}

// Artifact defines model for Artifact.
type Artifact struct {
	Name string `json:"name"`
	Path string `json:"path"`

	// Size Human-readable size, e.g. "1.13 GB"
	Size *string      `json:"size,omitempty"`
	Type ArtifactType `json:"type"`
}

// ArtifactType defines model for Artifact.Type.
type ArtifactType string

// ArtifactList defines model for ArtifactList.
type ArtifactList struct {
	Artifacts []Artifact `json:"artifacts"`
	BuildId   string     `json:"buildId"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`
}

// BuildAccepted defines model for BuildAccepted.
type BuildAccepted struct {
	BuildId string `json:"buildId"`

	// LogsUrl SSE endpoint for streaming logs
	LogsUrl string `json:"logsUrl"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`
}

// BuildDetails defines model for BuildDetails.
type BuildDetails struct {
	// Artifacts Partial outputs left on disk after a failed or cancelled build, so the
	// UI can point at their location.
	Artifacts *[]Artifact `json:"artifacts,omitempty"`
	BuildId   string      `json:"buildId"`
	CacheDir  string      `json:"cacheDir"`

	// Command The exact command that ran, for the troubleshoot panel
	Command string  `json:"command"`
	ErrMsg  *string `json:"errMsg,omitempty"`

	// HasLogFile A downloadable log file exists on disk
	HasLogFile bool `json:"hasLogFile"`

	// Residual Warning that a cancelled or failed build may have left the machine needing
	// manual cleanup. Present on `BuildDetails`, the SSE terminal event, and a
	// cancel response.
	Residual *ResidualIssue `json:"residual,omitempty"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`

	// Summary The human-readable summary shown in the Review panel and stored on the
	// build record for the Build Details panel.
	Summary  *ComposeSummary `json:"summary,omitempty"`
	Template string          `json:"template"`

	// TemplateUrl Download URL for the resolved template
	TemplateUrl string `json:"templateUrl"`
	WorkDir     string `json:"workDir"`
}

// BuildList defines model for BuildList.
type BuildList struct {
	Builds []HistoryItem `json:"builds"`
}

// BuildRequest Start a build. Carries exactly one of `compose` or `yaml` — never a diff.
//
// Exactly one of the two properties must be present. That constraint is
// machine-checkable via minProperties/maxProperties rather than left as
// prose: a body with neither field, or with both, is invalid and the server
// rejects it with 400 `NO_MATCH`.
//
// `oneOf` would express this more idiomatically, but oapi-codegen turns a
// `oneOf` with sibling properties into a `json.RawMessage` union type with
// custom (un)marshalling and two empty `interface{}` branch aliases —
// generated noise around the hot request path, and oapi-codegen does not
// enforce the constraint at runtime either way. The property-count form
// validates identically for a two-property schema and keeps the generated
// struct a plain pair of optional fields.
type BuildRequest struct {
	// Compose The UI selections that identify one combination. The backend uses these to
	// look up the matching pre-authored template in the manifest.
	Compose *ComposeRequest `json:"compose,omitempty"`

	// Yaml Complete template YAML (Advanced tab). Self-contained, not a delta.
	Yaml *string `json:"yaml,omitempty"`
}

// BuildStatus Build lifecycle state. `not-started` is the brief window after the build is
// accepted but before its process group exists (a cancel is already honoured
// there). `cancelling` lasts until the child finishes its own teardown.
type BuildStatus string

// CancelAccepted defines model for CancelAccepted.
type CancelAccepted struct {
	BuildId string `json:"buildId"`

	// Residual Warning that a cancelled or failed build may have left the machine needing
	// manual cleanup. Present on `BuildDetails`, the SSE terminal event, and a
	// cancel response.
	Residual *ResidualIssue       `json:"residual,omitempty"`
	Status   CancelAcceptedStatus `json:"status"`
}

// CancelAcceptedStatus defines model for CancelAccepted.Status.
type CancelAcceptedStatus string

// Combination Maps one valid UI selection to a pre-authored template file.
type Combination struct {
	ImageType string  `json:"imageType"`
	Os        string  `json:"os"`
	Platform  string  `json:"platform"`
	Sku       *string `json:"sku,omitempty"`

	// Template Filename in image-templates/. An empty string marks a planned combination whose template is not yet ready: the UI lists it but grays it out and refuses to compose/build it.
	Template string `json:"template"`
	Vertical string `json:"vertical"`
}

// ComposeRequest The UI selections that identify one combination. The backend uses these to
// look up the matching pre-authored template in the manifest.
type ComposeRequest struct {
	ImageType string  `json:"imageType"`
	Os        string  `json:"os"`
	Platform  string  `json:"platform"`
	Sku       *string `json:"sku,omitempty"`
	Vertical  string  `json:"vertical"`
}

// ComposeResponse defines model for ComposeResponse.
type ComposeResponse struct {
	// Summary The human-readable summary shown in the Review panel and stored on the
	// build record for the Build Details panel.
	Summary ComposeSummary `json:"summary"`

	// Template Resolved template filename
	Template string `json:"template"`

	// Yaml The matched template's YAML, verbatim
	Yaml string `json:"yaml"`
}

// ComposeSummary The human-readable summary shown in the Review panel and stored on the
// build record for the Build Details panel.
type ComposeSummary struct {
	Architecture string `json:"architecture"`

	// BaseImage Overlay-mode only — the baseline image packages are layered onto.
	BaseImage      *string `json:"baseImage,omitempty"`
	Description    string  `json:"description"`
	DiskSize       string  `json:"diskSize"`
	Hostname       string  `json:"hostname"`
	ImageName      string  `json:"imageName"`
	ImageType      string  `json:"imageType"`
	ImageVersion   string  `json:"imageVersion"`
	KernelVersion  string  `json:"kernelVersion"`
	Os             string  `json:"os"`
	PackageCount   int     `json:"packageCount"`
	PartitionCount int     `json:"partitionCount"`
	PartitionTable string  `json:"partitionTable"`
	Platform       string  `json:"platform"`
	Sku            string  `json:"sku"`
	Vertical       string  `json:"vertical"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// HistoryItem One row in the compose history list.
type HistoryItem struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`

	// Status Build lifecycle state. `not-started` is the brief window after the build is
	// accepted but before its process group exists (a cancel is already honoured
	// there). `cancelling` lasts until the child finishes its own teardown.
	Status BuildStatus `json:"status"`

	// Summary The human-readable summary shown in the Review panel and stored on the
	// build record for the Build Details panel.
	Summary  *ComposeSummary `json:"summary,omitempty"`
	Template string          `json:"template"`
}

// Manifest The complete configuration manifest, loaded once by the UI on startup.
type Manifest struct {
	Combinations []Combination `json:"combinations"`
	Platforms    []Option      `json:"platforms"`
	Skus         []Option      `json:"skus"`
	Targets      []Target      `json:"targets"`
	Verticals    []Option      `json:"verticals"`
}

// Option A generic {id, displayName} pair used for dropdown labels.
type Option struct {
	DisplayName string `json:"displayName"`
	Id          string `json:"id"`
}

// PackageRepoList defines model for PackageRepoList.
type PackageRepoList struct {
	Repos *[]struct {
		Description      *string `json:"description,omitempty"`
		DisplayName      *string `json:"displayName,omitempty"`
		EnabledByDefault *bool   `json:"enabledByDefault,omitempty"`
		Id               *string `json:"id,omitempty"`

		// Priority Repository priority (higher number = preferred when packages exist in multiple repos). Default 500.
		Priority *int    `json:"priority,omitempty"`
		Url      *string `json:"url,omitempty"`
	} `json:"repos,omitempty"`
}

// PackageSearchResults defines model for PackageSearchResults.
type PackageSearchResults struct {
	Packages *[]struct {
		Description *string `json:"description,omitempty"`
		Name        *string `json:"name,omitempty"`
		Repository  *string `json:"repository,omitempty"`

		// Version Latest available version
		Version *string `json:"version,omitempty"`
	} `json:"packages,omitempty"`
	Query *string `json:"query,omitempty"`
	Total *int    `json:"total,omitempty"`
}

// ResidualIssue Warning that a cancelled or failed build may have left the machine needing
// manual cleanup. Present on `BuildDetails`, the SSE terminal event, and a
// cancel response.
type ResidualIssue struct {
	// Detail Remediation detail: the failing signal error, or the tool's residual
	// cleanup report including its `mount | grep` / `losetup -l` hint.
	Detail string `json:"detail"`

	// Kind - `cancellation-failure` — the cancel signal could not be delivered (or
	//   the build never exited), so teardown may never have run.
	// - `cleanup-failure` — the build ran its teardown but reported leftover
	//   mounts or loop devices.
	Kind ResidualIssueKind `json:"kind"`
}

// ResidualIssueKind - `cancellation-failure` — the cancel signal could not be delivered (or
//
//		the build never exited), so teardown may never have run.
//	  - `cleanup-failure` — the build ran its teardown but reported leftover
//	    mounts or loop devices.
type ResidualIssueKind string

// Target An OS option with its family and architecture.
type Target struct {
	Arch        string `json:"arch"`
	DisplayName string `json:"displayName"`
	Id          string `json:"id"`
	Os          string `json:"os"`
}

// ValidationIssue defines model for ValidationIssue.
type ValidationIssue struct {
	Message *string `json:"message,omitempty"`

	// Path JSON path to the problematic field
	Path     *string                  `json:"path,omitempty"`
	Severity *ValidationIssueSeverity `json:"severity,omitempty"`
}

// ValidationIssueSeverity defines model for ValidationIssue.Severity.
type ValidationIssueSeverity string

// ValidationResponse defines model for ValidationResponse.
type ValidationResponse struct {
	Errors   *[]ValidationIssue `json:"errors,omitempty"`
	Valid    *bool              `json:"valid,omitempty"`
	Warnings *[]ValidationIssue `json:"warnings,omitempty"`
}

// BuildId defines model for BuildId.
type BuildId = string

// ListPackageReposParams defines parameters for ListPackageRepos.
type ListPackageReposParams struct {
	// Os Filter repos by target OS compatibility
	Os *string `form:"os,omitempty" json:"os,omitempty"`
}

// SearchPackagesParams defines parameters for SearchPackages.
type SearchPackagesParams struct {
	// Q Search query (package name prefix)
	Q string `form:"q" json:"q"`

	// Os Target OS distribution ID (e.g., ubuntu24)
	Os string `form:"os" json:"os"`

	// Repos Filter by enabled repository IDs
	Repos *[]string `form:"repos,omitempty" json:"repos,omitempty"`

	// Limit Max results to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ValidateTemplateJSONBody defines parameters for ValidateTemplate.
type ValidateTemplateJSONBody struct {
	// Yaml Complete template YAML to validate
	Yaml string `json:"yaml"`
}

// StartBuildJSONRequestBody defines body for StartBuild for application/json ContentType.
type StartBuildJSONRequestBody = BuildRequest

// ComposeTemplateJSONRequestBody defines body for ComposeTemplate for application/json ContentType.
type ComposeTemplateJSONRequestBody = ComposeRequest

// ValidateTemplateJSONRequestBody defines body for ValidateTemplate for application/json ContentType.
type ValidateTemplateJSONRequestBody ValidateTemplateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List the compose history
	// (GET /builds)
	ListBuilds(w http.ResponseWriter, r *http.Request)
	// Start an image build
	// (POST /builds)
	StartBuild(w http.ResponseWriter, r *http.Request)
	// List a build's output artifacts
	// (GET /builds/{id}/artifacts)
	ListBuildArtifacts(w http.ResponseWriter, r *http.Request, id BuildId)
	// Cancel a running build
	// (POST /builds/{id}/cancel)
	CancelBuild(w http.ResponseWriter, r *http.Request, id BuildId)
	// Get a build's command, resolved paths, and summary
	// (GET /builds/{id}/details)
	GetBuildDetails(w http.ResponseWriter, r *http.Request, id BuildId)
	// Get the full configuration manifest
	// (GET /manifest)
	GetManifest(w http.ResponseWriter, r *http.Request)
	// List available package repositories
	// (GET /package-repos)
	ListPackageRepos(w http.ResponseWriter, r *http.Request, params ListPackageReposParams)
	// Search available packages
	// (GET /packages/search)
	SearchPackages(w http.ResponseWriter, r *http.Request, params SearchPackagesParams)
	// Resolve the base template for a set of selections
	// (POST /templates/compose)
	ComposeTemplate(w http.ResponseWriter, r *http.Request)
	// Validate an edited template
	// (POST /templates/validate)
	ValidateTemplate(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBuilds operation middleware
func (siw *ServerInterfaceWrapper) ListBuilds(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuilds(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartBuild operation middleware
func (siw *ServerInterfaceWrapper) StartBuild(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartBuild(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBuildArtifacts operation middleware
func (siw *ServerInterfaceWrapper) ListBuildArtifacts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBuildArtifacts(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelBuild operation middleware
func (siw *ServerInterfaceWrapper) CancelBuild(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelBuild(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBuildDetails operation middleware
func (siw *ServerInterfaceWrapper) GetBuildDetails(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id BuildId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBuildDetails(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetManifest operation middleware
func (siw *ServerInterfaceWrapper) GetManifest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetManifest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPackageRepos operation middleware
func (siw *ServerInterfaceWrapper) ListPackageRepos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPackageReposParams

	// ------------- Optional query parameter "os" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "os", r.URL.Query(), &params.Os, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "os"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "os", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPackageRepos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPackages operation middleware
func (siw *ServerInterfaceWrapper) SearchPackages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPackagesParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Required query parameter "os" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "os", r.URL.Query(), &params.Os, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "os"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "os", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "repos" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "repos", r.URL.Query(), &params.Repos, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "repos"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repos", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPackages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ComposeTemplate operation middleware
func (siw *ServerInterfaceWrapper) ComposeTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ComposeTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ValidateTemplate operation middleware
func (siw *ServerInterfaceWrapper) ValidateTemplate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ValidateTemplate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds", wrapper.ListBuilds)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/builds", wrapper.StartBuild)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds/{id}/artifacts", wrapper.ListBuildArtifacts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/builds/{id}/cancel", wrapper.CancelBuild)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/builds/{id}/details", wrapper.GetBuildDetails)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/manifest", wrapper.GetManifest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/package-repos", wrapper.ListPackageRepos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/packages/search", wrapper.SearchPackages)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/templates/compose", wrapper.ComposeTemplate)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/templates/validate", wrapper.ValidateTemplate)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zHzpchs5lu6rnMh7IyxFc5Htqr591TE/vHWVum3LYUk1MVGsaIKZhyRKSCALQIqmPYqYX/MAE/OE/SQT",
	"5wC5kaDkqpFd/csWE4nl7MuH/JTlpqyMRu1ddvopq4QVJXq0/NfzWqrirKD/FuhyKysvjc5OwwOQBWov",
	"lxItHF1dnb08zkaZpMeV8OtslGlRYnaaySIbZRZ/qaXFIjv1tsZR5vI1loJm9tuKRjlvpV5lt7e3zUPe",
	"wjPr5VLknjdnTYXWS+QnYfZPGX4QZaVoinpRa18/+WZszcJ4mbuxKO3Eis1k9TEb7S40Ctvc38Eoc/Ij",
	"7h/6+7oUemxRFGKhEGjQCHCymsAsezx5/BS+ez7LslFvQ/HX1Nrhh08Z6rrMTn/MZClWmI0ytzBl9tPe",
	"C7d9Cv4Yzh4HxXN075jFz5h7WqQh3mvpEgQU8Sn/IT2W/J//a3GZnWb/Z9oJxjTyY9oyoz1AJqwVW/p7",
	"0cnKPj298PW9s7NQXYShuwduZm/nGvW2nzo6T/Ysz7HyWOyf/a7dKrNyV1btC8DFxStAXVRGag9LY8F5",
	"i6KUegX0zoD1U1HJ6c3jKS/kpmKRjx8/eTqN474OhZqDHKTPS/RCKnePaAyJ8I6eCQWm9lXtHShcejAa",
	"CumuQSw9WhCwFFJhAcZCLnSOiv7gDY7AGfBrnOmrM3oGgZjC04/SgjK5oIUmM03G5EsKZS7yNb6UNv3Q",
	"lKXQCct3uUbADyL3EIeAXwsPVugRi4RfI3hr6oVCtzbGQyU0qhTL0do3bpVcfS3ca7P6i1QJK/QMCrPR",
	"ykQrpMwKllLRpqTzruFEt+DCGIVCZywuTha1UPdR9H0cd+Zcjb9ROkeZq8tS2O19b72gnxxexNHERCwr",
	"JTwmSdM8TCroy0gZuHr/uuWGRWfUDRbQzptgxsbY67Qs3K9mjaz0dj7cZzd9T+oGXD6ooWnLHYzKZ5vt",
	"76Xzxm7PPJb7SpI63x0m9T3+UmPY045x9MJ6EEHNJ/BCWCvRBV1RWzAawSxhngd2z8k2zLeiVHP4x3/8",
	"N2i8YcNRyOVyMtMz/Wr4HqvVxkBHByhr52GBUFl0qP0ELkkRc6Odt4KMinQzXYp8LTWO8zXm16wwN1JA",
	"KfW7dqJpKT50f4EVfo0kOUIH2ybcTFfWODyl05liCxvp16BR8sClRDJrxoafF8avRyAdSH0jlCwgmAgE",
	"h/YG7UxbJHo6kD688M3JCczfnv/9zbPLF9/P+exzo/F8OYeNqVUB+IFO6MCvpYPSWARZSFMKL3Oh1HYE",
	"i9qDEZUc56bAFWrwtdUORG8iWsjJhSJX1SOh1N6AgPnPzujJe7F5g86JFc6h1tJoIAngd2c6r503JRzV",
	"+rgU1q2F4rn4cBsDWFZ+C3OpPdqlyPHT7RwWVuh8DUJJ4dARl2d6hRqt8FiANtIhCGvqSJ+18WCDcAEF",
	"NCOefHCuwqADbfxMo14amyO/2OM4GeJae1kiRO5sxJYEA5tTb8e5qYP3LmeBQ8ITJTiUZYKy4RB0rHHz",
	"EgRN4h1dI1aOF24PM6MN1DlJf6WE1FAJaUlqDSuHUEFIXHBqA3HLTh+PsoE48i9DdY8685mWtNHQ21FG",
	"+rWvqTROocfWIMK/PXvzGo6eFTfkrAvwYnE8gQtUy3FutBdSYzEiwpOCovJikqUC1LTBuGh9RyqFUHKJ",
	"+TancNoLjxOYa+PHjmwJFnPSI6L0wkpcwkbqwmxijME/hyzEzbSIgR7rwgKXrCXeEddz0p2VNXXVuMgj",
	"EaMSml4oCui3sDba1JZ4SXKDxxOYx9BF6tUclKA3SbZUELo1Lb2UWro1iQ953o0Gj8KSew6cbmL73pEo",
	"E6q1JpKRL2gW6P7gIa7OadvZKAuBVCIhGGUv+IXfFuI+QCTQHK53iHvTlj3nmXIzL0y5kFoEMdmVmjei",
	"cuwTgnG9OgOHCnPP5opsWWVxLGq/Nrbn8TlCIqEdUohzrsuYiO3RyLjkzzQhWY90onNd3xm17B+I3D9l",
	"cyA18H7GzVg3ncAzHU1rmApKYa9dMDNaY0ExaEMr2KyN6+m0ZFMJWySzKortKcvt1RkoVgLpWVdWVmz5",
	"D1N7Nm8WlzWZa28gmp1pVDM/GSQ4bbL94U9//Psfezn3z+Ljx+1YOjPZlsnA94Y4kAfhu1te2pE9sjNj",
	"Rj3e9ah7QJz6VjEZ0PfFyIWAPtY2QgDSI3PwJguRX6MuIJBqjUR4M9PKmGuoK6Z0KTyFHqsDEil1HKXl",
	"Ep0PBuP3Es8H5sidbHCV0cGXDU/7IOnCkLXvdyN/tgP92kmfCGlnedmwsjfNI8cecwQ3aBfCyzK7z/D1",
	"EgNepsuO7qDVRUeR/T2td4pRYSy4NbmhKFzv8UbiJmSgrNyUBlBarkMKHhTbYm5s0aZLwS/HykB4NyWc",
	"wuZr6TH3tU3L50I4POOi1t7+z2/QKrEdl6ZAMFptOQVgjy4cKqkxmEKoRH4tVuhAWAQlthh2780kxcDB",
	"IokdUV58ESt7+ym3cb6pKO495N28vfPpQT3lpz+gdYe2dY1Wo7prxCFVD9R5QQFtbwAF4Su0YYT1kujx",
	"OWMuSZB+Z5tCk91t6ztW7JB2yP/RUEB3qbxDvJ5s7BFtj0I9WUkp7ytrjd03b5j+mVKbYRH77fnl3/9y",
	"fvX2ZUrEy5CgDd8IakzOfknZ1L3GiNfs5to/xM74sPXUWfuFhX0t1wjWbBpjFKMJWId3OAzZD8lyi5RR",
	"PWNhJRkQPjvNKEcbU1qXool8sJrzl6lZ7VBTDmpHPcfQHT1F6jcxUEh7g7xJ6XKjl3JV2xASNtHFCJQR",
	"BdvOHGGxbUJBo4HzkrpKmfhe1PP5taZ+9J4oyDaq/fkTnleH5nLX9UNM44Vd4a9oglzy+NRMjSH73+9q",
	"T2N7nOivE4nQp2t3oJQYnVfpvOpZqGbIHD7JYgSFdJUSW7Kzt6GaUTsMMUJhTUUpLiixQOX2Vbj3btoh",
	"Fp+pJP2JUmd5F0z4e6xMukxqsTJDXuzsdBgwdBb1vEL9w9nbc5B6iRZJaVCvKC5pIpJk/DE8eDfdmfao",
	"oJk02QvQ5FqK59uXuBS18oP3l0I5TNXzAyW7dcirq7GpUN9IbZIdTyuNlT7GlHGpb09ORnuRc2WcZDvd",
	"vAJHa7laowVdlwu08C+U2CzRUki2WaPugjUus5DZL2vlZaUQmBHHE4ing29PTnoRXC8YqUNVvzvS2vvK",
	"nU6novITnmXCh5zkppwePmiqGLWnYIfk6QIpdHiPrlY+ITStBPwGuXpp8mu08MKUZa2Jpq8KGcOVPVbt",
	"t7cLfnucJ72gbTl24KWx8zF8SYVqLmkVXguPzoO4EVKF4nkbP3UrPPl/k8eTx7+FCaPslxrDhvcrJsYP",
	"YsdWSFLTDstUe8f4V2E1ZeKc2IteS9LYplMZYqhSbGEtbjAU/kN+zv0D0IiF1KuZLoWuhYKcdLCuJvAu",
	"dB/Ilc77PdX5iN+/uHgFHm0ptVCAN6h9qGuLmY41SBsz4pQHLniuVGJbYiGDjw9jQnWHDkMHdXLF61Hg",
	"xq0Jbp8Yox45aEp/Mx3PwNppSWFzVdMhuZo5L7lO/u+wsljNYQpzZRz6uoKxmsNa6liy6OSgmbihDUji",
	"hoOjx8enMz0GZUx1Oi3wZkr/e3rKOw8lEvoBCryROZ7Gf2nXFp2pLUUstdvOtDMltr85ZpbzUilYIKxR",
	"FX/mVoAs0EKsscKj/ilgeiPs1JfVVOZ+pzH/iLnyqDvjI/CmKwKRPBgS/llSV69lqlU8bkvIzKkxcae2",
	"OG+z3SgBkVs5d3sojF8gFKjkDae7R8bONPTq3aFVhh+kx+I49NNj1ZlJEh6zFNtaT4jy88iR/R3ECoDQ",
	"zPN2nkXto1Rg0Z6ddsHkdMSbHsvcsNqdOjOFt8M93F8sZqKOGh1IBQAxEtsPZjScX8TmS+h90emWopRq",
	"G7SvlxtOkqWNQwWEXx/ZHEjf7wt4YurLe0md/YfQupJGt0ZveIpkqnilXV1Fvp5fBAwLFz6xgF7WfRAp",
	"NaTzXy/O33KvjnTFhybbQiG3JkPLa2AgQlw6MWkADIltjEwaSQqJ5yjbBPudFpk7KHO42Mgzf36Yvkvs",
	"VOxPQ3p87oVpcfsPuNz+seknqZcm5G3aR8RcROCdvbiESxTlXpUsex4L2c/enbUVQK7aQcxxLVwao+Do",
	"7MXlMWxwMV4I16+osgVBy33rZz21atsNuajo79DIqx3aR65fbP/Hf/4XP6ENRKQGDy25oL7Tz6FztCvT",
	"m/RDMOQ8CReERjuwLC7WQ7BgF9yEH1+Qx35F3tjxxi/X0kFh8rpExg2Ehn3wPWYJ3tZ+3ZLn+8vLd+Rp",
	"vBW5D+2A70zb3ie+ODYybTOcQuHQGtdCMS6MotrpnKuaXUd8aU3ZoAJmetD4PpqvTDsSJtO9yebHoxZo",
	"cLmt8IJZDLmSqH2zKdrGBhdTZ3N+kX+deDeHUpI+gPRMjbfGU6hitx3YjZEHRQiahAMBrPqkUSEIWaPF",
	"2BkhboyVWUUuzPTR/LtXl9D420+yuGUU3PyYZt1nSHeQltNT4uOYUU7TmW6waS0OimIaX1vN1X3XIMy2",
	"TN610MV4Y6X3qPkPhdaBqT3FCaEK3nFgHnZz1jBuzltp5ILyHPIlc48f/JRjuXE445y2NRdVpWRAr01N",
	"7rF72oR4sDDFLsSECRkVP/hRL73qlDaS4HlQM1KTrBewZ08nJ5MTdjIValHJ+NPTiAplUzPt4EJJd/ke",
	"A2AkVaXTuEHnx0tpnZ/AG7SU4FFoAlKPSyxpTJh+po+CnkovPA0IAEnha3ccCMfxNHox+dkZHdsODio6",
	"i/OhLVFIdz3TR860G3C1vZFkE0RUMaKmF9YfB2q1MnhWUMIinX8eTstNbiY7n/zJyUljGzGUwvv8oh1x",
	"E6pFJd9bNOSSA9vdfXRFj4JsrNuyIm8wRWgu25CL+DGL+/+J3K5JFvysXK1IjAWxJ7ZKIuzqkgFvAUXD",
	"6IaN2LK97UE54CiirWaa0RzHLOZ5ErB1SgZh3INtNZHjc+FkPvZi0TPmf449nOBSlDHXbrcbSkFkuiFK",
	"e4imXHoQbixdCF47kJjvVzqxoAC419oj88mepAdjYXvWyHfEpsHZy2DLrcivIyBqxQirGynapK2zYCk5",
	"Y7AbMypC29H556bYPqyItUieYbTobY23e+L95GHXbnElCREPLcIWcxM6iwHecjvKvnlATQvNlMQWziK6",
	"rpF1Y0GbrueeD6vQ336NLQXnEZJu4GJ+qDk0WdbG2GtXiZDatnX/oXmIIErdV+qUabgdZQOHOsBr32vk",
	"A3Qb2pfgKCzH/pPZefH8/M1xBMJFy3JFYd9iy/io3qtcVAo+e7FtrbY1m4ijICdMOe0wJrvTdj9rDzMa",
	"3Ef5Mc2Ybsi0ua9y+9MXtP6DSxWHtaM9BKvEN19e/p7vtAETjicy85HbE4FfJWTTT5RX3Gann3aHhNyf",
	"862k64oWzUG/SEAhNom8Hi+VXK1935dFn+9QFw7mF2ffXb56/2bOuUGrWY92cX4hAIxwqui57NhTHhNw",
	"exVabpY0uL2ZbksfR7XmIofUq1G6QuWCv8QP9DIHNhSmw+OnJzGXQMiFCuBCt9X52hptandKbs1GLZw/",
	"OXnSwHI5RBqgDdsQmPYVa4cMj4SjeVu8nHNhbx7ql3OQyx4uMRSHQBs9fvz05Jghkl1FKcA/drzcIxec",
	"PPnWeahU8nHOwrxNjUrovQIVeebSkA1eUpC9wFzUDnuYZ7C1djNNu7HGhATH1CEMcrmpKPJ2dWHgWio1",
	"B1srbN19GzpLF4t9TLqZXtS+DVkEzJvi45yE6Vrq4kDtLaLEY4pntNoyuLusPGmOXEadbCDn8bUROKlz",
	"MmQ7xVyuuC2NUmaTMmkBotnECQ9myx7O1e9gSFPhbF9RG5f/5wH8FrTZQA8G+rsZPFr3/3+tdSO+spGy",
	"RRRail0jpNiiYNiYgKEWs+JKP9NrQXOEdKqxYKycJOxBdY5Eg89ib1pZDHh1MUiDhqY+sIyGxCr4Z4cR",
	"RXcf7N4gwmJlTVHnciGV9Ntp/9ITQ1XRi0J4MYSkXZ09cjOdG6VE5SQRbRbpGdeeZQFzFupHh25asW3c",
	"u9gDR38A0ZYF4Or96+PQhanQjrsgbMp3cGa6kBZzb8iEBIu7WSMn5uLOK1YpRf8O/eBC3T9l4DLY4UG5",
	"bmTgnyNs+Q77UUsUhFF3p4uLHIF7zUufIefKrJbhcl3iiUv83IP30KOyB8b5rJIKZ6zNW6QLgjzKSsVQ",
	"gQwH/Rtymj7aA8xyphu8x/Tib1fTpkw/Pb+YtsA4KEVFfjTU4aUdIl7dCCpVUwwQGgwRusHxPdmo2CoJ",
	"EdfVGYSiGpshBgx1MCEiNIUSVsYyLeTC5YK7hg0wxPElTqW2BxSlRTJ9QVFv10gI3F9qpVpeJMSN/T6N",
	"SWOpevLVrhIkLCIDxi3s5E7RiKOhbdxLjClTLiiKgogJaSxnv6wx00c4WU1GMESWjKABGLwawfvzC3gC",
	"fxUfP26bcS9MWdUe4X24I3WwgtYD1iRM2d79Bc9Fuco4RpZxkwfOL1juhY/uofkyQGj4t58G4PkPfwrg",
	"S1rDXfRQQlJ6KBglw42qr19JIGUk9erLSTK3a0EaKcnqSe27BsAykFo3ddg0PpNyG2AxbDM6WHa7ptSt",
	"vA4EOpQQVvIGdRSNyUxfhB6kYwSR/NCWbdoiQ3Da8RhhXyBqbxpTOtMJpXjkoDkaOI9Vsm7Hc73rQFx3",
	"ynY8MsssHDX74ds6YefHB8T6lzs/eFFK/Rr1yq+z0yeJjuZeubfVqELSqEXN9ujsJUQj0NzEOb5LyT7/",
	"+xujAyq+2O6zeAtnL92BZW00H91KbfPzwNcwuvbm/rWvD+Tza+X5ZlJIow+sq2Qp/WDdFun25ISvX8qy",
	"LrPTb0/2EWhfw+IM8WUJ9X/T3hxq5PRrV1WNhVI6ilCi8PfU5HcxgsEGDGkyLJxGI7FrBO8wfN09u979",
	"2nTZKiTIsS3c9a6PmsBsBBd/uxq1CIoRnF+MYgmXJOw4hE22FxSmb4cN+tvN5aIQvIGY6QN3fprGdP+6",
	"z/CaGl+cfnt+OdNuq/0anfzIVegS7Qo5P2166iGDHbRuYqDq0fX7LTPdDzmlG1xFbBopvdttscne7yjT",
	"QcZ8/YfC99CTKk0hlzLGlvG6UrNkssISWHfZwei/RDdm92b15/RjTh5+9YhmOdx07H3j4p+zEfPNkydf",
	"fkupK3sNztMbDqimzc3/38echfSV6MN/hACvD3nYsW7xImN7Ra53LI6vHHowy55p6lm9RjX2zV5Lg4N2",
	"74f2+wiiS2OHXw0QKyF17GkPzFf3yYTO8gm9DRQIXaYGGDUKWSiXw0UAjnFiP4HnIr92odqzE+rN2s3N",
	"MljU3lOSaqAyG+TLCpZ7DMDf/Yg5MRbSu5mOnwfg9J6CTkYuhT55s88nJyfNbm5aLFYMQOCo/bxR75lk",
	"Ax3v7S9rxXn9cQ8S01m+tvnAJo6CSd7kCJxpv0hB8sCYC5q4/YoEX9jmzHspnEc7AqnHlRI5whKxIGuf",
	"spENoR7ASA5RdL/q8xLeQCtw90E/eeKfkiC3r2d2EzjChF7/sC8fbQwVPwFz/NWM8RuhSLSwM8cL4vDv",
	"Y+Ni8blTkh2j1oglCL0L5jhkvhgnSmuksrXXJhcKCrxBZSoG8oWxWbxWwndJTqdTrk6tjfOnfzr500n8",
	"ThtXXuOa+wKdqgPB0YGK3R9gWGY77lKTriw1OnBX/fAXLBp4yx6Espu+o9X+/O9S5SYywjtpdhNM9s1t",
	"t8K7LiM5gEriOUujaYk+iqG3zViWvf3p9n8CAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
