# Userdata partition (1087 MiB, ext4, mounted at /opt)
# Sized to match OIC default: 6 GiB total - 512M ESP - 4044M root - 500M roothashmap = 1087M
[Partition]
Type=linux-generic
Label=userdata
Format=ext4
SizeMinBytes=1087M
SizeMaxBytes=1087M
