name: gitleaks
on: [pull_request, push, workflow_dispatch]

permissions:
  contents: read
  pull-requests: read
  security-events: write
  actions: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Run Gitleaks scan
        id: gitleaks
        uses: ./.github/actions/security/gitleaks
        with:
          scan-scope: "all"
          source: "./"
          version: "8.28.0"
          config_path: ".github/gitleaks.toml"
          report_format: "sarif"
          redact: "true"
          exit_code_on_leak: "1"